### ISSUE TITLE
There must be at least 1 Vif as upstream.

### ISSUE THREAD

**Issue by lllibailll** [fabianishere/udm-iptv#1]
So I have the same problem as in fabianishere/udm-kernel-tools#22 

UniFi OS UDM Pro 1.11.0-14

My setup:

GPON ONT -> WAN ethernet port of UDMP and PPPoE WAN.
LAN: 10.69.1.0/24
Both Internet and IPTV are on VLAN 24

My logs:
```
udm-iptv: Obtaining IP address for VLAN interface...
ip: RTNETLINK answers: File exists
run-parts: /etc/network/if-pre-up.d/vlan: exit status 2
udm-iptv: NATing IPTV network ranges (if necessary)...
udm-iptv: Setting up igmpproxy..
udm-iptv: Starting igmpproxy..
adding VIF, Ix 0 Fl 0x0 IP 0x0101450a br0, Threshold: 1, Ratelimit: 0
There must be at least 1 Vif as upstream.
```

My 15-iptv.sh:

```
IPTV_WAN_INTERFACE="eth8"
IPTV_WAN_RANGES="239.192.0.0/16"
IPTV_WAN_VLAN="24"
IPTV_WAN_DHCP_OPTIONS="-O staticroutes -V IPTV_RG"
IPTV_LAN_INTERFACES="br0"
IPTV_LAN_RANGES="10.69.1.0/24"

if podman container exists iptv; then
  podman rm -f iptv
fi
podman run --network=host --privileged \
    --name iptv -i -d --restart always \
    -e IPTV_WAN_INTERFACE="$IPTV_WAN_INTERFACE" \
    -e IPTV_WAN_RANGES="$IPTV_WAN_RANGES" \
    -e IPTV_WAN_VLAN="$IPTV_WAN_VLAN" \
    -e IPTV_WAN_DHCP_OPTIONS="$IPTV_WAN_DHCP_OPTIONS" \
    -e IPTV_LAN_INTERFACES="$IPTV_LAN_INTERFACES" \
    -e IPTV_LAN_RANGES="$IPTV_LAN_RANGES" \
    fabianishere/udm-iptv -d -v
```

**Comment by osterlitz** [comment]
This configuration is working for me on MagentaTV / DE on a BGN fiber connection with UDM (non-pro).

```
IPTV_WAN_INTERFACE="ppp0"
IPTV_WAN_RANGES="224.0.0.0/4 87.141.0.0/16 193.158.0.0/15"
IPTV_WAN_VLAN="0"
IPTV_WAN_DHCP_OPTIONS="-O staticroutes -V IPTV_RG"
IPTV_LAN_INTERFACES="br16 br42 br0 br8"
IPTV_IGMPPROXY_ARGS="-d -v"
```

****
Combinations with/without VLAN 7 and eth4 didn't work as that interface never receives an IP.
The proxy will only start once the ppp connection is up, this happens a while after the S15 boot execution.
I renamed the script to 95-iptv.sh and added these lines before the "podman run" line to trigger/delay the connection:

```
> sysctl net.ipv4.conf.all.force_igmp_version=3
> ping -w 5 google.de
> sleep 30
```
 If the proxy comes up too early, you can restart the container manually, a good indicator.
 
With my (1.11) UDM I also needed to add firewall policies to allow inbound UDP and IGMP for the  IPTV_WAN_RANGES on the "WAN in" firewall section. Of course IGMP snooping has to be enabled.
The " sysctl net.ipv4.conf.all.force_igmp_version=3" above is necessary for the MediaReceiver as it requires IGMPv3, the MagentaTV app doesn"t need this. I will crosspost this to the manual section as well.

**Comment by fabianishere** [comment]
Closing this issue for now, since it is related to the old version of `udm-iptv`. If it appears again, we can re-open it.
