### ISSUE TITLE
IPTV not working after update

### ISSUE THREAD

**Issue by rdebeuze** [fabianishere/udm-iptv#102]
Hello,

Today i have updated igmp proxy using apt install ./igmpproxy_0.3-1_arm64.deb and updated iptv using apt inudm stall ./udm-iptv_2.1.0_all.deb 

After a reboot of my udm pro tv still doesn't work. I have the log off igmp proxy in the attachments.

Can somebody help me?

Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth8
WAN Ranges: 213.75.0.0/16 217.166.0.0/16
WAN VLAN: 4 (dev iptv)
WAN DHCP options: -O staticroutes -V IPTV_RG
LAN Interfaces: br185
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
=== Service Logs ===
Mar 20 23:22:53 ubnt udm-iptv[14378]: Sending discover...
Mar 20 23:22:53 ubnt udm-iptv[14378]: Sending select for 10.95.25.6...
Mar 20 23:22:53 ubnt udm-iptv[14378]: Lease of 10.95.25.6 obtained, lease time 3600
Mar 20 23:22:53 ubnt udm-iptv[14378]: NATing IPTV network ranges (if necessary)
Mar 20 23:22:53 ubnt udm-iptv[14378]: Setting up igmpproxy
Mar 20 23:22:54 ubnt udm-iptv[14378]: Starting igmpproxy
Mar 20 23:22:54 ubnt udm-iptv[14378]: MC-Router API already in use; Errno(98): Address already in use
Mar 20 23:22:54 ubnt systemd[1]: udm-iptv.service: Main process exited, code=exited, status=255/EXCEPTION
Mar 20 23:22:54 ubnt systemd[1]: udm-iptv.service: Failed with result 'exit-code'.
Mar 20 23:22:54 ubnt systemd[1]: udm-iptv.service: Consumed 204ms CPU time.
[log.txt](https://github.com/fabianishere/udm-iptv/files/8312304/log.txt)

**Comment by fabianishere** [comment]
You already have igmpproxy (or something similar) running already. 
Did you upgrade from the old Docker-based setup of this project? If not, perhaps try rebooting your device.

**Comment by rdebeuze** [comment]
Yes i have updated from this project. So i have to uninstall the old version of igmp proxy? After a few reboots my tv is stable now.

**Comment by fabianishere** [comment]
If you used the Docker-based setup, you’ll need to delete the file you created in `/mnt/data/on_boot.d`. If not, you don’t have to do anything.
