### ISSUE TITLE
BT Profile isnt working for me

### ISSUE THREAD

**Issue by kopvm** [fabianishere/udm-iptv#106]
### What is your ISP? (if relevant)

BT

### Diagnostic Information

Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth8
WAN Ranges: 224.0.0.0/4  109.159.247.0/24
WAN VLAN: 0 (dev )
WAN DHCP options: -O staticroutes
LAN Interfaces: br0  br10
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
=== Service Logs ===
Apr 12 01:49:29 ubnt udm-iptv[8270]: ip: invalid argument 'change' to 'ip'
Apr 12 01:49:29 ubnt udm-iptv[8270]: NATing IPTV network ranges (if necessary)
Apr 12 01:49:29 ubnt udm-iptv[8270]: Setting up igmpproxy
Apr 12 01:49:30 ubnt udm-iptv[8270]: Starting igmpproxy
Apr 12 01:49:30 ubnt udm-iptv[8270]: adding VIF, Ix 0 Fl 0x0 IP 0x010c0b0a br0, Threshold: 1, Ratelimit: 0
Apr 12 01:49:30 ubnt udm-iptv[8270]: adding VIF, Ix 1 Fl 0x0 IP 0x010d0b0a br10, Threshold: 1, Ratelimit: 0
Apr 12 01:49:30 ubnt udm-iptv[8270]: There must be at least 1 Vif as upstream.
Apr 12 01:49:30 ubnt systemd[1]: udm-iptv.service: Main process exited, code=exited, status=255/EXCEPTION
Apr 12 01:49:30 ubnt systemd[1]: udm-iptv.service: Failed with result 'exit-code'.
Apr 12 01:49:30 ubnt systemd[1]: udm-iptv.service: Consumed 95ms CPU time.

### Describe the Bug

Hi there,

First thanks for your help on this service.

I am trying to use the BT profile however I cannot seem to get it to work. My setup is a Vigor 166 modem is upstream and I have a pppoe connection in unifi to my ISP.

Any help you could provide would be greatly appreciated.

Thanks
Jamie

### Expected Behavior

Im not sure if the bt profile is compatible with pppoe connections

**Comment by kopvm** [comment]
One more piece of info. If i change the interface to ppp0 I get the following output minus my ip address :) Tv still doesnt work
Please share the following output with the developers:
=== Configuration ===
WAN Interface: ppp0
WAN Ranges: 224.0.0.0/4  109.159.247.0/24
WAN VLAN: 0 (dev )
WAN DHCP options: -O staticroutes
LAN Interfaces: br10
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
27: ppp0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1492 qdisc pfifo_fast qlen 3
    inet xxx.xxx.xxx.xxx peer 172.16.14.226/32 scope global ppp0
       valid_lft forever preferred_lft forever
172.16.14.226 dev ppp0  src xxx.xxx.xxx.xxx
=== Service Logs ===
Apr 12 02:05:37 ubnt udm-iptv[12713]: The IGMP message was from myself. Ignoring.
Apr 12 02:05:37 ubnt udm-iptv[12713]: RECV V2 member report   from 10.11.13.1      to 224.0.0.22
Apr 12 02:05:37 ubnt udm-iptv[12713]: The IGMP message was from myself. Ignoring.
Apr 12 02:05:38 ubnt udm-iptv[12713]: RECV V2 member report   from 10.11.13.13     to 224.0.1.187
Apr 12 02:05:38 ubnt udm-iptv[12713]: Inserted route table entry for 224.0.1.187 on VIF #0
Apr 12 02:05:38 ubnt udm-iptv[12713]: Joining group 224.0.1.187 on interface ppp0
Apr 12 02:05:39 ubnt udm-iptv[12713]: Route activation request from xxx.xxx.xxx.xxx for 233.89.188.1 is from myself. Ignoring.
Apr 12 02:05:40 ubnt udm-iptv[12713]: The IGMP message was local multicast. Ignoring.
Apr 12 02:05:40 ubnt udm-iptv[12713]: RECV V2 member report   from 10.11.13.1      to 224.0.0.251
Apr 12 02:05:40 ubnt udm-iptv[12713]: The IGMP message was from myself. Ignoring.

**Comment by kopvm** [comment]
Hi there,

Unfortunately that still didnt work using eth8 or ppp0 as the interface. I have included the eth8 output below:
Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth8
WAN Ranges: 224.0.0.0/4  109.159.247.0/24
WAN VLAN: 0 (dev )
WAN DHCP options: -O staticroutes
LAN Interfaces: br10
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
=== Service Logs ===
Apr 12 16:47:37 ubnt udm-iptv[12147]: Usage: ip [OPTIONS] {address | route | link | tunnel | rule} {COMMAND}
Apr 12 16:47:37 ubnt udm-iptv[12147]: ip [OPTIONS] OBJECT {COMMAND}
Apr 12 16:47:37 ubnt udm-iptv[12147]: where OBJECT := {address | route | link | tunnel | rule}
Apr 12 16:47:37 ubnt udm-iptv[12147]: OPTIONS := { -f[amily] { inet | inet6 | link } | -o[neline] }
Apr 12 16:47:37 ubnt udm-iptv[12147]: Starting igmpproxy
Apr 12 16:47:37 ubnt udm-iptv[12147]: adding VIF, Ix 0 Fl 0x0 IP 0x010d0b0a br10, Threshold: 1, Ratelimit: 0
Apr 12 16:47:37 ubnt udm-iptv[12147]: There must be at least 1 Vif as upstream.
Apr 12 16:47:37 ubnt systemd[1]: udm-iptv.service: Main process exited, code=exited, status=255/EXCEPTION
Apr 12 16:47:37 ubnt systemd[1]: udm-iptv.service: Failed with result 'exit-code'.
Apr 12 16:47:37 ubnt systemd[1]: udm-iptv.service: Consumed 100ms CPU time.

Thanks again for your help. It really is appreciated!

**Comment by kopvm** [comment]
I have just installed iproute2

**Comment by kopvm** [comment]
Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth8
WAN Ranges: 224.0.0.0/4  109.159.247.0/24
WAN VLAN: 0 (dev )
WAN DHCP options: -O staticroutes
LAN Interfaces: br10
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
=== Service Logs ===
Apr 12 16:58:20 ubnt systemd[1]: Started IPTV support for the UniFi Dream Machine.
Apr 12 16:58:20 ubnt udm-iptv[2252]: NATing IPTV network ranges (if necessary)
Apr 12 16:58:20 ubnt udm-iptv[2252]: Monitoring interface eth8 for changes
Apr 12 16:58:20 ubnt udm-iptv[2252]: Setting up igmpproxy
Apr 12 16:58:20 ubnt udm-iptv[2252]: Starting igmpproxy
Apr 12 16:58:20 ubnt udm-iptv[2252]: adding VIF, Ix 0 Fl 0x0 IP 0x010d0b0a br10, Threshold: 1, Ratelimit: 0
Apr 12 16:58:20 ubnt udm-iptv[2252]: There must be at least 1 Vif as upstream.
Apr 12 16:58:20 ubnt systemd[1]: udm-iptv.service: Main process exited, code=exited, status=255/EXCEPTION
Apr 12 16:58:20 ubnt systemd[1]: udm-iptv.service: Failed with result 'exit-code'.
Apr 12 16:58:20 ubnt systemd[1]: udm-iptv.service: Consumed 97ms CPU time.

**Comment by kopvm** [comment]
Everything started working instantly when I did that.  Thanks again for all your support

**Comment by fabianishere** [comment]
Cool! I will soon release a version with this issue fixed, so it should work out of the box.
