### ISSUE TITLE
KPN dev iptv missing after upgrading to 2.1.2 on UDM PRO

### ISSUE THREAD

**Issue by gerbenp** [fabianishere/udm-iptv#111]
### What is your ISP? (if relevant)

KPN

### Diagnostic Information

Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth8
WAN VLAN: 4 (dev iptv)
WAN DHCP: true (options "-O staticroutes -V IPTV_RG")
WAN Ranges: 213.75.0.0/16 217.166.0.0/16
LAN Interfaces: br661
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
=== Service Logs ===
Apr 16 11:18:02 ubnt systemd[1]: Started IPTV support for the UniFi Dream Machine.
Apr 16 11:18:02 ubnt udm-iptv[9971]: Device iptv already exists.. Deleting device
Apr 16 11:18:02 ubnt udm-iptv[9971]: Obtaining IP address for VLAN interface
Apr 16 11:18:02 ubnt udm-iptv[9971]: udhcpc (v1.22.1) started
Apr 16 11:18:02 ubnt udm-iptv[9971]: Sending discover...
Apr 16 11:18:03 ubnt udm-iptv[9971]: Sending select for 10.242.50.41...
Apr 16 11:18:03 ubnt udm-iptv[9971]: Lease of 10.242.50.41 obtained, lease time 3600
Apr 16 11:18:03 ubnt udm-iptv[9971]: NATing IPTV network ranges (if necessary)
Apr 16 11:18:03 ubnt systemd[1]: udm-iptv.service: Succeeded.
Apr 16 11:18:03 ubnt systemd[1]: udm-iptv.service: Consumed 49ms CPU time.

### Describe the Bug

My IPTV is not working anymore with the 2.1.2 version, missing an output of the iptv entry when entering ip -4 addr show dev iptv command. It shows nothing. Tried to reboot all my network gear and decoders, but no result.

Using an config with an seperate VLAN 661 with IGMP enabled.

Debug info at 2.1.2:
root@ubnt:/# ip -4 addr show dev iptv

ip route list shows:
root@ubnt:/# ip route list
192.168.0.0/24 dev br0 proto kernel scope link src 192.168.0.254
192.168.1.0/24 dev br661 proto kernel scope link src 192.168.1.254
192.168.30.0/24 dev br30 proto kernel scope link src 192.168.30.254
195.190.228.5 dev ppp0 proto kernel scope link src 86.86.76.37
203.0.113.0/24 dev dnsfilter proto kernel scope link src 203.0.113.1

journalctu -u udm-iptv on 2.1.2:
Apr 16 11:55:08 ubnt systemd[1]: Stopping IPTV support for the UniFi Dream Machine...
Apr 16 11:55:08 ubnt igmpproxy[10417]: select() failure; Errno(4): Interrupted system call
Apr 16 11:55:08 ubnt systemd[1]: udm-iptv.service: Succeeded.
Apr 16 11:55:08 ubnt systemd[1]: Stopped IPTV support for the UniFi Dream Machine.
Apr 16 11:55:08 ubnt systemd[1]: udm-iptv.service: Consumed 254ms CPU time.
Apr 16 11:55:08 ubnt systemd[1]: Started IPTV support for the UniFi Dream Machine.
Apr 16 11:55:08 ubnt udm-iptv[4014]: Device iptv already exists.. Deleting device
Apr 16 11:55:08 ubnt udm-iptv[4014]: Obtaining IP address for VLAN interface
Apr 16 11:55:08 ubnt udm-iptv[4014]: udhcpc (v1.22.1) started
Apr 16 11:55:08 ubnt udm-iptv[4014]: Sending discover...
Apr 16 11:55:09 ubnt udm-iptv[4014]: Sending select for 10.242.49.169...
Apr 16 11:55:09 ubnt udm-iptv[4014]: Lease of 10.242.49.169 obtained, lease time 3600
Apr 16 11:55:09 ubnt udm-iptv[4014]: NATing IPTV network ranges (if necessary)
Apr 16 11:55:09 ubnt systemd[1]: udm-iptv.service: Succeeded.
Apr 16 11:55:09 ubnt systemd[1]: udm-iptv.service: Consumed 51ms CPU time.

When i downgrade to 2.0.5 it works again, debug info aswell:
root@ubnt:/# ip -4 addr show dev iptv
49: iptv@eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    inet 10.242.49.169/20 brd 10.242.63.255 scope global iptv
       valid_lft forever preferred_lft forever

udm-iptv-diag on 2.0.5:
Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth8
WAN Ranges: 213.75.0.0/16 217.166.0.0/16
WAN VLAN: 4 (dev iptv)
WAN DHCP options: -O staticroutes -V IPTV_RG
LAN Interfaces: br661
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: false
=== IP Link and Route ===
49: iptv@eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    inet 10.242.49.169/20 brd 10.242.63.255 scope global iptv
       valid_lft forever preferred_lft forever
10.242.48.0/20 proto kernel scope link src 10.242.49.169
213.75.112.0/21 via 10.242.48.1 metric 249
=== Service Logs ===
Apr 16 11:36:29 ubnt systemd[1]: Started IPTV support for the UniFi Dream Machine.
Apr 16 11:36:29 ubnt udm-iptv[10417]: Device iptv already exists.. Deleting device
Apr 16 11:36:29 ubnt udm-iptv[10417]: Obtaining IP address for VLAN interface
Apr 16 11:36:29 ubnt udm-iptv[10417]: udhcpc (v1.22.1) started
Apr 16 11:36:29 ubnt udm-iptv[10417]: Sending discover...
Apr 16 11:36:29 ubnt udm-iptv[10417]: Sending select for 10.242.49.169...
Apr 16 11:36:29 ubnt udm-iptv[10417]: Lease of 10.242.49.169 obtained, lease time 3600
Apr 16 11:36:29 ubnt udm-iptv[10417]: NATing IPTV network ranges (if necessary)
Apr 16 11:36:29 ubnt udm-iptv[10417]: Setting up igmpproxy
Apr 16 11:36:29 ubnt udm-iptv[10417]: Starting igmpproxy

Upgraded with the command as described on the README.md. Removed it aswell and reinstalled it back with a reboot.

### Expected Behavior

Excepted that it will works as before on 2.0.5.

**Comment by fabianishere** [comment]
Hi @gerbenp, thanks for the report. This is indeed a regression introduced by [some new functionality](https://github.com/fabianishere/udm-iptv/commit/1762369e2bc95387d381392c93f98f4f38e4d408).

https://github.com/fabianishere/udm-iptv/commit/d7dae9b0cbcd3f02e49bd95a50cb4d396f260ef4 should resolve the issue. Could you try installing v2.1.3 which I just released and check whether it fixes the issue?

**Comment by gerbenp** [comment]
Updated to 2.1.3 and it seems to be working!

That's a quick fix 😄 

Thanks! Some coffee for the fast support 😎
