### ISSUE TITLE
Vivo SP option gives wrong settings

### ISSUE THREAD

**Issue by apedroheringer** [fabianishere/udm-iptv#115]
### What is your ISP? (if relevant)

Vivo SP

### Diagnostic Information

root@ubnt:/# udm-iptv-diag
Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth8
WAN VLAN: 20 (dev iptv)
WAN DHCP: true (options "-O staticroutes -V IPTV_RG")  **I configured using custom settings**
WAN Ranges: 172.28.0.0/14 201.0.52.0/23 200.161.71.0/24 177.16.0.0/16
LAN Interfaces: br20
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: false
=== IP Link and Route ===
83: iptv@eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    inet 10.154.188.196/20 scope global iptv
       valid_lft forever preferred_lft forever
10.154.176.0/20 proto kernel scope link src 10.154.188.196
172.28.0.0/14 via 10.154.176.1 metric 283
177.16.30.0/23 via 10.154.176.1 metric 288
200.161.71.40/30 via 10.154.176.1 metric 285
200.161.71.46/31 via 10.154.176.1 metric 286
200.161.71.48/31 via 10.154.176.1 metric 287
201.0.52.0/23 via 10.154.176.1 metric 284
=== Service Logs ===
Apr 20 16:45:37 ubnt systemd[1]: Started IPTV support for the UniFi Dream Machine.
Apr 20 16:45:37 ubnt udm-iptv[17261]: Device iptv already exists.. Deleting device
Apr 20 16:45:37 ubnt udm-iptv[17261]: Obtaining IP address for VLAN interface
Apr 20 16:45:37 ubnt udm-iptv[17261]: udhcpc (v1.22.1) started
Apr 20 16:45:37 ubnt udm-iptv[17261]: Sending discover...
Apr 20 16:45:37 ubnt udm-iptv[17261]: Sending select for 10.154.188.196...
Apr 20 16:45:37 ubnt udm-iptv[17261]: Lease of 10.154.188.196 obtained, lease time 7200
Apr 20 16:45:37 ubnt udm-iptv[17261]: NATing IPTV network ranges (if necessary)
Apr 20 16:45:37 ubnt udm-iptv[17261]: Setting up igmpproxy
Apr 20 16:45:37 ubnt udm-iptv[17261]: Starting igmpproxy

### Describe the Bug

Sets IPTV_WAN_DHCP_OPTIONS to false

### Expected Behavior

It must be set to -O staticroutes -V IPTV_RG to iptv work

**Comment by apedroheringer** [comment]
Actually the bug heappenss because it's settings DHCP to false...

**Comment by fabianishere** [comment]
Fixed by [136a3b2](https://github.com/fabianishere/udm-iptv/commit/136a3b22458c54656ad7f8d583a3e502be02b441)
