### ISSUE TITLE
v1.11 firmware not accessible

### ISSUE THREAD

**Issue by coret** [fabianishere/udm-iptv#12]
The [firmware version 1.11](https://community.ui.com/releases/UniFi-OS-Dream-Machines-1-11-0-14/) link leads to a http 404 error (even when logged in the community). Not yet released or beta which is only available to beta-testers?

**Comment by fabianishere** [comment]
This is a beta release that is indeed only visible for members participating in the Ubiquiti early-access programme. If you don't/can't enroll for the beta program, see this "mirror" of the release notes: https://unifi-forum.nl/onderwerpen/unifi-os-dream-machines-1-11-0-19.2595/
