### ISSUE TITLE
BT profile when using the BT HomeHub and UDM Pro

### ISSUE THREAD

**Issue by kopvm** [fabianishere/udm-iptv#122]
### What is your ISP? (if relevant)

BT

### Diagnostic Information

Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth8
WAN VLAN: 0 (dev )
WAN DHCP: true (options "-O staticroutes")
WAN Ranges: 224.0.0.0/4 109.159.247.0/24
LAN Interfaces: br10
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: false
=== IP Link and Route ===
4: eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 10.20.30.1/24 scope global eth8
       valid_lft forever preferred_lft forever
    inet 192.168.1.199/24 scope global dynamic eth8
       valid_lft 86001sec preferred_lft 86001sec
10.20.30.0/24 proto kernel scope link src 10.20.30.1 
192.168.1.0/24 proto kernel scope link src 192.168.1.199 
=== Service Logs ===
May 15 13:16:45 ubnt udm-iptv[9963]: NATing IPTV network ranges (if necessary)
May 15 13:16:45 ubnt udm-iptv[9963]: Monitoring interface eth8 for changes
May 15 13:16:45 ubnt udm-iptv[9963]: Setting up igmpproxy
May 15 13:16:45 ubnt udm-iptv[9963]: Starting igmpproxy
May 15 13:16:49 ubnt igmpproxy[9963]: can't join group 224.0.1.187 on interface eth8; Errno(98): Address already in use
May 15 13:16:50 ubnt igmpproxy[9963]: can't join group 234.81.130.251 on interface eth8; Errno(98): Address already in use
May 15 13:16:51 ubnt igmpproxy[9963]: can't join group 234.81.132.20 on interface eth8; Errno(98): Address already in use
May 15 13:16:54 ubnt igmpproxy[9963]: can't join group 234.81.132.21 on interface eth8; Errno(98): Address already in use
May 15 13:17:04 ubnt igmpproxy[9963]: can't join group 234.81.132.20 on interface eth8; Errno(98): Address already in use
May 15 13:18:07 ubnt igmpproxy[9963]: can't join group 239.255.255.250 on interface eth8; Errno(98): Address already in use
root@ubnt:/# 

### Describe the Bug

I am trying to use the udm pro with my bt home hub infront of it. The way that it is setup is its a dhcp connection and the homehub has a dmz pointing all the traffic to the UDM.

In the past i have been able to set it up like this and get the iptv working however no matter what settings I change I cant seem to get it working this time.

Any insight would be greatly appreciated.

### Expected Behavior

IPTV to work with the bt homehub infront of the UDM pro with the UDM using a DHCP connection instead of PPPOE

**Comment by bfayers** [comment]
> I got it working by adding a couple of firewall rules.
> 
> Thanks again for your work on this.

Any chance you could provide the information on this....?

**Comment by blair287** [comment]
> I got it working by adding a couple of firewall rules.
> 
> Thanks again for your work on this.

Its so unhelpful when people don't post what fixed it.....

**Comment by bfayers** [comment]
> Its so unhelpful when people don't post what fixed it.....

Perhaps, but this package is long since obselete (at least for BTTV) with the UDM's built in IPTV handling now.

**Comment by blair287** [comment]
> > Its so unhelpful when people don't post what fixed it.....
> 
> Perhaps, but this package is long since obselete (at least for BTTV) with the UDM's built in IPTV handling now.

Never fixed it for me
