### ISSUE TITLE
UDM-Pro firmware version 1.12.x configuration not persistent across upgrades

### ISSUE THREAD

**Issue by jpatriarca** [fabianishere/udm-iptv#125]
### What is your ISP? (if relevant)

Meo PT

### Diagnostic Information

Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth9
WAN VLAN: 0 (dev iptv)
WAN DHCP: false (options "-O staticroutes -V IPTV_RG")
WAN Ranges: 10.159.0.0/16  10.173.0.0/16  194.65.46.0/23  213.13.16.0/20  224.0.0.0/4
LAN Interfaces: br40
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
3: eth9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 10000
    inet 85.245.19.93/24 scope global dynamic eth9
       valid_lft 3221sec preferred_lft 3221sec
85.245.19.0/24 proto kernel scope link src 85.245.19.93
=== Service Logs ===
May 25 14:00:00 ubnt udm-iptv[5835]: The IGMP message was local multicast. Ignoring.
May 25 14:00:00 ubnt udm-iptv[5835]: RECV V2 member report   from 192.168.40.1    to 233.89.188.1
May 25 14:00:00 ubnt udm-iptv[5835]: The IGMP message was from myself. Ignoring.
May 25 14:00:02 ubnt udm-iptv[5835]: RECV V2 member report   from 192.168.40.1    to 224.0.0.2
May 25 14:00:02 ubnt udm-iptv[5835]: The IGMP message was from myself. Ignoring.
May 25 14:00:03 ubnt udm-iptv[5835]: RECV V2 member report   from 192.168.40.30   to 232.0.7.7
May 25 14:00:03 ubnt udm-iptv[5835]: Updated route entry for 232.0.7.7 on VIF #1
May 25 14:00:03 ubnt udm-iptv[5835]: Adding MFC: 10.173.5.53 -> 232.0.7.7, InpVIf: 0
May 25 14:00:03 ubnt udm-iptv[5835]: Adding MFC: 10.173.5.51 -> 232.0.7.7, InpVIf: 0
May 25 14:00:04 ubnt udm-iptv[5835]: The IGMP message was local multicast. Ignoring.

### Describe the Bug

I'm using EA firmwares on my UDM-Pro and I'm seeing that, contrary to what documentation states, udm-iptv app does not keep configuration across upgrades. Taking in consideration that the configuration is placed in /etc/udm-iptv.conf and withing unifi-os podman container, the configuration don't remain available when the container is upgraded as this could be the root cause of the issue.

Not sure if this is an expected behavior or just a bug, but something I'm facing since I've installed the app (was using the podman container before, and my config would persist with firmware upgrade).

Checking details on the container, I see that it have **srv** folder mounted in udm-pro local storage, so it could be interesting for your app to have the option to set up the configuration file and be read from the persistant storage location rather than etc folder.

### Expected Behavior

App install and configuration would be persistent with firmware upgrades

**Comment by fabianishere** [comment]
I believe this is the same issue as #120 and that it is not possible to have a persistent installation. My recommendation would be to make a backup of `/etc/udm-iptv.conf` manually.

**Comment by jpatriarca** [comment]
Thank you. This is not exactly the same issue as #120 as the installation is persistent but the configuration file is deleted after a firmware install. The alternative was to use /srv/ folder in unifi-os container for the config file since that folder is mapped in the container and it's located in the udm-pro storage in /mnt/data_ext/unifi-os folder.

So there's two issues, one with install persistence with UDR and configuration persistence in your configuration since the /etc/ folder is container storage and it's not persistent when the unifi-os container is update (fw upgrade).

Is there an alternative?

**Comment by fabianishere** [comment]
@jpatriarca You are right. I have tried to address this with #127, though you need to re-create the symlink after a firmware upgrade.
