### ISSUE TITLE
STB Unable to update after updating umd-iptv Issue

### ISSUE THREAD

**Issue by mattam1234** [fabianishere/udm-iptv#130]
### Discussed in https://github.com/fabianishere/udm-iptv/discussions/129

<div type='discussions-op-text'>

<sup>Originally posted by **mattam1234** May 29, 2022</sup>
Device:       UDM Pro
Provider:    KPN
Settings:
IPTV on VLan 4
and Internet on VLan 6

Problem:    Getting F309 at updating screen gathering an update from KPN on about 27%

Story:
The program was running fine for a while and there where no issues.
After a bit of time it started to drop the video and audio connection and you would have to switch channels and switch back.
I am not shore where this problem came from so I tried updating umd-iptv with little effect from like 15 minutes of watch time I got like an hour or so.
So it was more stable but if you would be watching a movie switching channels would be frustrating.
And so I tried reinstalling the program and broke something.
At this moment of time the STB is trying to get an update that isn't there/unreachable and it wont start.

I'm shore I broke something but if someone have a bit of time I would be very thankful

Note: I don't know if this is related but I also tried disabling the pi hole and network monitor with no effect.

Logs udm-iptv-diag:

> === Configuration ===
> WAN Interface: eth8
> WAN VLAN: 4 (dev iptv)
> WAN DHCP: true (options "-O staticroutes -V IPTV_RG")
> WAN Ranges: 213.75.0.0/16  217.166.0.0/16
> LAN Interfaces: br0  br4
> IGMP Proxy quickleave disabled: false
> IGMP Proxy debug: true
> === IP Link and Route ===
> 57: iptv@eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
>     inet 10.254.96.228/21 brd 10.254.103.255 scope global iptv
>        valid_lft forever preferred_lft forever
> 10.254.96.0/21 proto kernel scope link src 10.254.96.228
> 213.75.112.0/21 via 10.254.96.1 metric 257
> === Service Logs ===
> May 29 21:46:42 ubnt udm-iptv[10167]: RECV V2 member report   from 192.168.2.126   to 224.0.0.251
> May 29 21:46:42 ubnt udm-iptv[10167]: Updated route entry for 224.0.0.251 on VIF #0
> May 29 21:46:42 ubnt udm-iptv[10167]: The IGMP message was local multicast. Ignoring.
> May 29 21:46:43 ubnt udm-iptv[10167]: RECV V2 member report   from 192.168.2.246   to 239.255.255.251
> May 29 21:46:43 ubnt udm-iptv[10167]: Updated route entry for 239.255.255.251 on VIF #0
> May 29 21:46:43 ubnt udm-iptv[10167]: RECV V2 member report   from 192.168.2.242   to 226.1.1.1
> May 29 21:46:43 ubnt udm-iptv[10167]: Updated route entry for 226.1.1.1 on VIF #0
> May 29 21:46:44 ubnt udm-iptv[10167]: RECV V2 member report   from 192.168.2.246   to 230.0.0.10
> May 29 21:46:44 ubnt udm-iptv[10167]: Updated route entry for 230.0.0.10 on VIF #0
> May 29 21:46:44 ubnt udm-iptv[10167]: The IGMP message was local multicast. Ignoring.
> 

Thanks
</div>

**Comment by fabianishere** [comment]
Is your STB connected directly to the UDM Pro? If not, could you try connecting directly and check if the issue persists?

**Comment by mattam1234** [comment]
Yes the STB is directly connected to the UDM Pro.

**Comment by mattam1234** [comment]
Checking the next day and it started working again i really don't know what's changed.
Still thanks for your time and the great program.
