### ISSUE TITLE
Update 1.12.22 broke IPTV

### ISSUE THREAD

**Issue by Jordenjj** [fabianishere/udm-iptv#133]
### What is your ISP? (if relevant)

XS4ALL (KPN)

### Diagnostic Information

=== Configuration ===
WAN Interface: eth8
WAN Ranges: 213.75.0.0/16 217.166.0.0/16
WAN VLAN: 4 (dev iptv)
WAN DHCP options: -O staticroutes -V IPTV_RG
LAN Interfaces: br0
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: false
=== IP Link and Route ===
ip: can't find device 'iptv'
ip: can't find device 'iptv'
=== Service Logs ===
-- Logs begin at Thu 2022-06-02 12:38:37 CEST, end at Thu 2022-06-02 13:20:40 CEST. --
-- No entries --

### Describe the Bug

Since upgrading the OS to 1.12.22 IPTV stopped working. When trying to reinstall the following is reported:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 udm-iptv : Depends: iproute2 but it is not installable
E: Unable to correct problems, you have held broken packages.

```

### Expected Behavior

Working IPTV

**Comment by fabianishere** [comment]
What does `apt install iproute2` say?

**Comment by gotiniens** [comment]
For me it is working on 1,12,22
