### ISSUE TITLE
igmpproxy breaks after uplink is reconnected

### ISSUE THREAD

**Issue by MirkoKas** [fabianishere/udm-iptv#142]
### What is your ISP? (if relevant)

Deutsche Telekom

### Diagnostic Information

-

### Describe the Bug

After a restart of my UDM-Pro the udm-iptv service is starting but because (I think) there is not an IP from my provider yet, it fails to run. A manual restart via systemctl restart udm-iptv fixes the issue. 

### Expected Behavior

Start the service only if there is an IP or check for it after start and do a restart of the service automatically.

**Comment by MirkoKas** [comment]
Actually I don’t have any good idea how to measure the time. 
I just had a short disconnect/reconnect of my ISP. The UDM pro reconnected PPoE with no problem after a couple of seconds, but udm-iptv lost it’s data flow on ppoe0 and needed a restart of the service to get back running. 
Is there a way to implement a check and if not do a service restart automatically. I remember that on the old USG you could run periodically a script to check wether the IGMP-proxy was working or not as the proxy was a little picky sometimes. Maybe something like that could help here too?

**Comment by Schachter87** [comment]
Hello everyone,
the problem is a bit older, but still relevant. With each IP change, the IGMP proxy loses its function and must be configured manually. However, the settings are retained.

Since switching to 2.4, the restart function no longer exists, so that a cronjob no longer works either.

Is there a solution to this?

**Comment by fabianishere** [comment]
@Schachter87 could you try switching to improxy and check if that fixes the problem?

**Comment by Schachter87** [comment]
It seems that there are no problems when selecting IGMPv3 via improxy. I'll keep an eye on this for now. Thank you Fabian for the tip.

**Comment by WW1983** [comment]
> Bei der Auswahl von IGMPv3 über Improxy scheint es keine Probleme zu geben. Ich werde das vorerst im Auge behalten. Danke Fabian für den Tipp.
> 
> EDIT 30.03.2023: Ich beobachte das beschriebene Problem nun über einen längeren Zeitraum bei Ihrer Lösung (Umstellung auf IGMPv3). Seitdem habe ich keine Probleme mehr mit der Wiederherstellung der Verbindung und der Proxy läuft einwandfrei. Danke für deine Arbeit.

I have the same problem. Unfortunately, I don't know anything about it. Can someone explain to me how to set it up

**Comment by Schachter87** [comment]
Run "udm-iptv configure" and select the variant "improxy and IGMPv3". Switching from to improxy IGMPv3 worked for me
![Screenshot 2023-06-21 110843](https://github.com/fabianishere/udm-iptv/assets/97608733/ce5a9b66-c7f3-4d24-877f-21db4e0cfe17)
![Screenshot 2023-06-21 110911](https://github.com/fabianishere/udm-iptv/assets/97608733/c834bdb0-25a1-4189-97f8-2d6fae61dc52)

**Comment by WW1983** [comment]
> Run "udm-iptv configure" and select the variant "improxy and IGMPv3". Switching from to improxy IGMPv3 worked for me ![Screenshot 2023-06-21 110843](https://user-images.githubusercontent.com/97608733/247497087-ce5a9b66-c7f3-4d24-877f-21db4e0cfe17.png) ![Screenshot 2023-06-21 110911](https://user-images.githubusercontent.com/97608733/247497098-c834bdb0-25a1-4189-97f8-2d6fae61dc52.png)

Thank you!!
