### ISSUE TITLE
Must be 1 Vif as upstream

### ISSUE THREAD

**Issue by HammerDownT680** [fabianishere/udm-iptv#144]
### What is your ISP? (if relevant)

Telus Optik TV

### Diagnostic Information

root@ubnt:/# udm-iptv-diag 
Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth8
WAN VLAN: 2 (dev iptv)
WAN DHCP: true (options "-O staticroutes -V IPTV_RG")
WAN Ranges: 207.0.0.0/8 209.0.0.0/8 216.0.0.0/8
LAN Interfaces: br2
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: false
=== IP Link and Route ===
=== Service Logs ===
Jul 13 01:20:45 ubnt systemd[1]: udm-iptv.service: Scheduled restart job, restart counter is at 63.
Jul 13 01:20:45 ubnt systemd[1]: Stopped IPTV support for the UniFi Dream Machine.
Jul 13 01:20:45 ubnt systemd[1]: udm-iptv.service: Consumed 189ms CPU time.
Jul 13 01:20:45 ubnt systemd[1]: Started IPTV support for the UniFi Dream Machine.
Jul 13 01:20:45 ubnt udm-iptv[30198]: Device iptv already exists.. Deleting device
Jul 13 01:20:45 ubnt udm-iptv[30198]: Obtaining IP address for VLAN interface
Jul 13 01:20:45 ubnt udm-iptv[30198]: udhcpc (v1.22.1) started
Jul 13 01:20:45 ubnt udm-iptv[30198]: Sending discover...
Jul 13 01:20:48 ubnt udm-iptv[30198]: Sending discover...
Jul 13 01:20:51 ubnt udm-iptv[30198]: Sending discover...
root@ubnt:/# udm-iptv-diag 
Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth8
WAN VLAN: 2 (dev iptv)
WAN DHCP: true (options "-O staticroutes -V IPTV_RG")
WAN Ranges: 207.0.0.0/8 209.0.0.0/8 216.0.0.0/8
LAN Interfaces: br2
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: false
=== IP Link and Route ===
=== Service Logs ===
Jul 13 01:20:51 ubnt udm-iptv[30198]: Sending discover...
Jul 13 01:20:55 ubnt udm-iptv[30198]: udhcpc failed to get a DHCP lease
Jul 13 01:20:55 ubnt udm-iptv[30198]: No lease, forking to background
Jul 13 01:20:55 ubnt udm-iptv[30198]: NATing IPTV network ranges (if necessary)
Jul 13 01:20:55 ubnt udm-iptv[30198]: Setting up igmpproxy
Jul 13 01:20:55 ubnt udm-iptv[30198]: Starting igmpproxy
Jul 13 01:20:55 ubnt igmpproxy[30198]: There must be at least 1 Vif as upstream.
Jul 13 01:20:55 ubnt systemd[1]: udm-iptv.service: Main process exited, code=exited, status=255/EXCEPTION
Jul 13 01:20:55 ubnt systemd[1]: udm-iptv.service: Failed with result 'exit-code'.
Jul 13 01:20:55 ubnt systemd[1]: udm-iptv.service: Consumed 174ms CPU time.
root@ubnt:/# 

### Describe the Bug

IGMP Proxy is not working. IPTV freezes every 15 seconds. Receiving error about having at least 1 Vif as upstream. IGMP Proxy will work as a standalone if I was to use it with a basic configuration file (see below). It will not work however using UDM-IPTV. 

- upstream = modem interface
phyint eth8 upstream ratelimit 0 threshold 1
        altnet 0.0.0.0/0;

- lan interface of iptv device
phyint br2 downstream ratelimit 0 threshold 1
        altnet 10.69.2.1/24;

- disable all unused interfaces
phyint lo disabled
phyint eth8 disabled

### Expected Behavior

I would assume it would not be receiving these errors, would also create an interface called "iptv" which it does not and IPTV would be working as intended.

**Comment by fabianishere** [comment]
You should set `IPTV_WAN_VLAN` to zero. Right now, it is trying to setup a connection to VLAN 2 on your WAN port.

**Comment by HammerDownT680** [comment]
Ah ok understood. Any way to have it run within that VLAN on the LAN side?

**Comment by fabianishere** [comment]
You have selected `br2` as LAN interface, so it will connect to your VLAN 2 on the LAN side.

**Comment by HammerDownT680** [comment]
RIGHT! Whoops. Now its coming together. It works now. That will teach me to play around with this stuff in the middle of the night. Ugh. One last question, I don't see a device named "iptv" when listing all devices. Normal? And thank you by the way!!!

**Comment by fabianishere** [comment]
Yes, you will only see an `iptv` device if you use a VLAN on the WAN side.
