### ISSUE TITLE
UDM Pro & IPTV XS4ALL troubles..

### ISSUE THREAD

**Issue by Marcelvm78** [fabianishere/udm-iptv#15]
Hi, 

I'm not a networkguy so this is all quite challenging for me, i understand the concepts but to be honest is all the stuff through the ssh more typing what is recommended then really my expertise...

I tried following the procedure to get my UDM Pro configured with IPTV but i keep struggling to get the tv-boxes to work. Internet works fine.

- Running UDM Pro on 1.11.0-20 
- WAN connected to Fiber-modem, setup with PPP0E on VLAN 6
- My ports of UDM are connected as:
- P1 - Linked to EdgeMax 24p (just used as switch)
- P2 - TV box
- P3 - TV box
- P6 - TV box
- P9 - WAN to FC modem 
- Got bootscript installed
- IGM snooping turned on at IPTV VLAN 4 settings
- DHCP options added to IPTV VLAN 4 settings
    - Broadcast  28  IP Address 192.168.1.255
    - Parameter_Request 55 Text 1,3,28,121 
    - IPTV 60 Text IPTV_RG

ip -4 addr show dev iptv
28: iptv@eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    inet 10.59.34.21/20 brd 10.59.47.255 scope global iptv
       valid_lft forever preferred_lft forever

![image](https://user-images.githubusercontent.com/95151440/143724382-6d89a475-2213-41f5-bc26-99ab92743f99.png)

It all looks good but whenever i reboot the tv boxes they keep coming to error message at 85%

I hope you got some ideas to help me out.

thanks
Marcel

**Comment by fabianishere** [comment]
Hi Marcel,

Do you know why you have the following route:
```
213.75.112.0/21 dev br4 proto static scope link metric 1
```
This means that all traffic destined for the IPTV network is routed back to one of your internal VLANs (VLAN ID 4).
Do you by any chance have installed a static route in the UniFi interface for `213.75.112.0/21`?

**Comment by Marcelvm78** [comment]
Hi Fabian,

No, i don't have any static routes configured. I now removed it from ssh with:
sudo ip route del 213.75.112.0/21 dev br4 proto static scope link metric 1 

Then restarted one of the TV boxes but it comes with new software and once it tries to download it says it can't download the software DBS-307 error, tried to reset the TV box also but it keeps getting to try to download the software. Happens on all tv boxes.

Also tried restarting the UDM pro console but after this when i ssh into it and run a ip route show it displayes the same static route again.

**Comment by fabianishere** [comment]
Could you try using different DNS servers for the IPTV VLAN?

As for the static route, you need to check in the UniFi interface if you have configured the `213.75.112.0/21` CIDR somewhere.

**Comment by Marcelvm78** [comment]
I changed the DNS servers for IPTV VLAN and got a bit further now, it retrieves the software when starting the tv boxes but then gets to a point where it let you switch channels but screen remains black and then message occurs STB-NMC-400 :-( Tried factory resetting them but error remains.

If i look at the steps i did to get this working from https://github.com/fabianishere/udm-iptv i do doubt some things, in DHCP option my broadcast address is the one from my IPTV LAN, 192.168.**2.**255 (where my normal LAN is 192.168.**1**.x), should that be the correct one for the DHCP option? Also after the step to get it running with /mnt/data/on_boot.d/15-iptv.sh i see the following output:

# /mnt/data/on_boot.d/15-iptv.sh
2c2b3e280e36c725d4577895c5fe6f421d815ff17aefe2e2bddf8f0bdd7aad50
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
23d75c94446763b3f09307208ddd2efc1088855766ac8d28047b7e92c193ab26

Not sure if that is the correct output?

I did not powered off the UDM pro console yet, then shutdown Fibermodem, then start fibremodem and then start UDM Pro again. Maybe that helps. Also the UI does not show any static route anywhere so i don't know why this route keeps coming back after power cycle.

**Comment by fabianishere** [comment]
Don’t worry about the warnings, that’s expected. I believe the DHCP options are also correct.

What are the contents of `/mnt/data/on_boot.d/15-iptv.sh`?

**Comment by Marcelvm78** [comment]
# cat /mnt/data/on_boot.d/15-iptv.sh
IPTV_WAN_INTERFACE="eth8"
IPTV_WAN_RANGES="213.75.0.0/16 217.166.0.0/16"
IPTV_WAN_VLAN="4"
IPTV_WAN_DHCP_OPTIONS="-O staticroutes -V IPTV_RG"
IPTV_LAN_INTERFACES="br0 br4"

if podman container exists iptv; then
  podman rm -f iptv
fi
podman run --network=host --privileged \
    --name iptv -i -d --restart on-failure:5 \
    -e IPTV_WAN_INTERFACE="$IPTV_WAN_INTERFACE" \
    -e IPTV_WAN_RANGES="$IPTV_WAN_RANGES" \
    -e IPTV_WAN_VLAN="$IPTV_WAN_VLAN" \
    -e IPTV_WAN_DHCP_OPTIONS="$IPTV_WAN_DHCP_OPTIONS" \
    -e IPTV_LAN_INTERFACES="$IPTV_LAN_INTERFACES" \
    -e IPTV_LAN_RANGES="" \
    fabianishere/udm-iptv

**Comment by fabianishere** [comment]
Have you set the ports connected to the IPTV receivers to the right port profile (so VLAN ID 4 is untagged)?

**Comment by Marcelvm78** [comment]
The ports for the Receivers (port 2 & 3) are set to the IPTV switch port profile,  See my comment on the IPTV switch port profile, this might have a wrong setup...?

Port 2
![image](https://user-images.githubusercontent.com/95151440/143880945-67a0ebdc-2080-4abe-a3ec-93eac90927cf.png)

Port 3
![image](https://user-images.githubusercontent.com/95151440/143881008-1dc97f54-efe7-4697-bcd6-200f2d2ff7cd.png)

IPTV switch port profile settings
![image](https://user-images.githubusercontent.com/95151440/143881939-d699d32f-c4b1-4efb-81b2-77f3e9b449f0.png)


**The IPTV Network** 
![image](https://user-images.githubusercontent.com/95151440/143880496-6608f7ac-ed53-4b0d-a2c9-3b5247faa1c3.png)

**Comment by fabianishere** [comment]
The port profile is correct.

The broadcast address of the IPTV network is not as far as I can tell; it should be `192.168.2.255`.
Also, it is not necessary to manually define DHCP option 55.

**Comment by Marcelvm78** [comment]
Hi, changed broadcast IP in DHCP options now, then it still would not work. Then restarted UDM Pro console, for some reason the static route keeps coming back, so removed it again. Then IPTV worked on both tv's now.. haleluja..

I hope it keeps working now, thanks for all your tips Fabian! 🥇

**Comment by fabianishere** [comment]
Awesome!

You could try adding the route removal command to the boot script, so you don’t have to do it manually every time the UDMP boots.

**Comment by Marcelvm78** [comment]
Yes, need to find out how to do that, not sure how easy that is to edit the bootscript.

**Comment by Marcelvm78** [comment]
well.. happiness was just for a short moment, even though both tv's worked for some time it's back to the STB-NMC-400 message again..  static route is still not back..

**Comment by fabianishere** [comment]
I suspect igmpproxy is crashing. Could you check whether the `iptv` container is still running:
```shell
podman ps
```

I have read about issues with a Chromecast being present in the network and crashing igmpproxy. If you change `IPTV_LAN_INTERFACES` in `/mnt/data/on_boot.d/15-iptv.sh` to `br4` (which I recommend anyway), only the traffic from the IPTV VLAN is processed by igmpproxy, so devices other than the IPTV receiver won't interfere with the IPTV traffic.

**Comment by Marcelvm78** [comment]
# podman ps
CONTAINER ID  IMAGE                                   COMMAND     CREATED            STATUS                PORTS  NAMES
67d45ea36a05  docker.io/fabianishere/udm-iptv:latest              About an hour ago  Up About an hour ago         iptv
cef60af494cb  localhost/unifi-os:latest               /sbin/init  2 days ago         Up About an hour ago         unifi-os

**Comment by Marcelvm78** [comment]
I do have 3 chromecasts running yes so hopefully that was it. Modified it now and cycled UDM Pro console, works again now

**Comment by Marcelvm78** [comment]
Also it seems to keep adding the static route "213.75.112.0/21 dev br4 proto static scope link metric 1" even while it runs, not sure why it does that. It also just crashed again, restarted it and back online.

**Comment by Marcelvm78** [comment]
It now works but crashes each approx 5 minutes, only way to get it back then is to cylce UDM Pro console, then remove the static route and then it works for next 5 mins..

**Comment by Marcelvm78** [comment]
i'm thinking on putting a router before it, then connect that to Fibremodem, use  3 ports of that to use for TV and 4th port to UDM Pro solely for Internet then.. just wondering which one to buy as i do got about 15 connected devices on the UDM pro so i guess the router before should be powerfull enough or would it not matter..

**Comment by fabianishere** [comment]
If you go that route, my suggestion would be to just use the router you got from XS4All (if you got one).

Just to check, did you remove the DHCP Option 55 from your IPTV VLAN configuration? 
Do the static routes get added if you disable the boot script?

**Comment by Marcelvm78** [comment]
nah it's still in there (option 55), i need to check how to disable the boot script.

**Comment by Marcelvm78** [comment]
i don't got the fritzbox anymore, was seeing the draytek vigor 2135 which seems to be a good one also

**Comment by fabianishere** [comment]
I recommend you remove it, perhaps that’s causing the static route. 

As for disabling the boot script, just move the file (`mnt/data/on_boot.d/15-iptv.sh`) out of the on_boot.d directory temporarily.

**Comment by Marcelvm78** [comment]
ok removed the option 55, after cycle of UDMP i don't see the static route yet.. perhaps that causes to to break.. let's see for now how long it lasts..

**Comment by Marcelvm78** [comment]
still working.. will monitor for now.. so far still good..

**Comment by Marcelvm78** [comment]
Hasn't stopped yet, so seems to have done the trick!

**Comment by xHuubx** [comment]
Hello Marcel, what internet provider do you have? On the XS4ALL website they mention the dhcp 55 - parameter-request-list https://www.xs4all.nl/klant/instellingen-routed-mode-televisie-voor-ander-modem/

**Comment by Marcelvm78** [comment]
Hi, i am using XS4ALL.. that's why I also added it earlier, but when this option 55 is set it doesn't work anymore, the static route Fabian mentioned earlier is then added then and iptv fails. Since i removed the option 55 all works perfect and IGMP proxy remains running. Somehow this 55 option does something that makes the IGMP proxy to fail/crash.

Thanks

**Comment by xHuubx** [comment]
Okay great, I would be interested in the settings for XS4ALL, in the end you filled in:
`IPTV_LAN_INTERFACES="br4"`
without the br0 right? And the 4 here represents your IPTV vlan ?

**Comment by Marcelvm78** [comment]
Yes, without the br4, correct.
