### ISSUE TITLE
Magenta TV not working properly - stuck after ~10-15 seconds

### ISSUE THREAD

**Issue by leifbln** [fabianishere/udm-iptv#17]
Hi Fabian, 

thanks for your work to make IPTV happen on the UDM. 

Unfortunately i followed your guidance and was not able to use IPTV with MagentaTV on my UDM. 

The Stream is stopping after 10-15 seconds.

My Setup is the following: 

Speedport 4 from Deutsche Telekom in Modem-Mode -> TP-Link Managed Switch with Tagged VLAN7 -> Unifi Dream Machine -> Magenta TV Receiver MR401

The only difference I experienced was that the command **ip -4 addr show dev iptv** was not bringen me an Output: 

```
ip -4 addr show dev iptv
Device "iptv" does not exist.
```

Think this should be there? 

If I use **podman logs iptv** I can see lot of entries with the Magenta TV Addresses. 

Would be great if you could advise if i'm doing something wrong.

Firewallrules are in place like described here: 

(https://www.bjoerns-techblog.de/2017/06/deutsche-telekom-entertain-mit-dem-ubiquiti-unifi-security-gateway)

 Thanks, 

Leif

**Comment by fabianishere** [comment]
Have you seen the existing issues/discussions on Magenta TV? 

See https://github.com/fabianishere/udm-iptv/discussions/8 for instance.

**Comment by leifbln** [comment]
Sorry, moved it to the discussion!
