### ISSUE TITLE
after running dpkg-reconfigure -p medium udm-iptv instead of the configuration screen get a black screen

### ISSUE THREAD

**Issue by CristianMori** [fabianishere/udm-iptv#201]
### Diagnostic Information

none

### Describe the Bug

after a UDM update, run dpkg-reconfigure -p medium udm-iptv and get a blank screen
uninstalled, rebooted, reinstalled, same

### Expected Behavior

get configuration screen

**Comment by fabianishere** [comment]
As workaround, please modify `/etc/udm-iptv.conf` directly for now.

Which UDM version are you running at the moment? And is it a UDM or UDM Pro?
