### ISSUE TITLE
Upgrading UDM-Pro to Unifi OS 2.0 / 2.5 / 3.0 Cause isues?

### ISSUE THREAD

**Issue by MiranoVerhoef** [fabianishere/udm-iptv#212]
Hello,

Just now ubiquiti released their EA for the new OS2.0 for the UDM Pro:

[[https://community.ui.com/releases/UniFi-OS-Dream-Machines-2-4-23/aebbba64-9e7e-4151-bcca-34ed08761f08]](https://community.ui.com/releases/UniFi-OS-Dream-Machines-2-4-23/aebbba64-9e7e-4151-bcca-34ed08761f08)

Is this release supported since it runs on a different base OS?

Also, is there a way to donate in the form of support?

**Comment by jpatriarca** [comment]
It should support like UDM-Pro SE version. The issue is that the configuration is maintained eached but need to reinstall udm-iptv any time a firmware is updated.

**Comment by bvk007** [comment]
No no issues, just updated my UDM base to 2.4 and did a reinstall of the software. All works

**Comment by HammerDownT680** [comment]
So under this EA 2.0 etc OS, will it remain intact during restarts? Obviously can't follow the instructions to move the config to /mnt/persistent so just curious how this works without containers now. Will it have to be reinstalled even after minor firmware updates?

**Comment by jpatriarca** [comment]
> So under this EA 2.0 etc OS, will it remain intact during restarts? Obviously can't follow the instructions to move the config to /mnt/persistent so just curious how this works without containers now. Will it have to be reinstalled even after minor firmware updates?
> 
> Im now running under EA version 2.4.26. installed this evening.

Check my comment above. I'm just waiting for a new EA version to validate that perspective.
