### ISSUE TITLE
UNA 7.4.140 contains IGMP Proxy

### ISSUE THREAD

**Issue by Calimerorulez** [fabianishere/udm-iptv#223]
In the release notes of the Network App version 7.4.140, which is still in EA, Ubiquiti has implemented: - Add support for IPTV through IGMP Proxy (for UXG/UniFi OS Consoles with gateway functions).

**Comment by fabianishere** [comment]
Thanks for letting us know. I checked quickly, but it does not seem like it supports providers like KPN (where IPTV is on a separate VLAN)  in its current form.
