### ISSUE TITLE
Maximum number of multicast groups were exceeded

### ISSUE THREAD

**Issue by richardleeps** [fabianishere/udm-iptv#228]
### What is your ISP? (if relevant)

KPN

### Diagnostic Information

root@UDM-SE:~# udm-iptv diagnose
Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth8
WAN VLAN: 4 (dev iptv)
WAN DHCP: true (options "-O staticroutes -V IPTV_RG")
WAN Ranges: 213.75.0.0/16  217.166.0.0/16
LAN Interfaces: br0
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
46: iptv@eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    inet 10.214.85.183/21 brd 10.214.87.255 scope global iptv
       valid_lft forever preferred_lft forever
10.214.80.0/21 proto kernel scope link src 10.214.85.183 
213.75.112.0/21 via 10.214.80.1 metric 246 
=== Service Logs ===
Feb 04 17:46:52 UDM-SE udm-iptvd[97216]: Check settings of '/sbin/sysctl net.ipv4.igmp_max_memberships'
Feb 04 17:46:52 UDM-SE udm-iptvd[97216]: RECV V2 member report   from 192.168.3.17    to 239.73.192.62
Feb 04 17:46:52 UDM-SE udm-iptvd[97216]: Inserted route table entry for 239.73.192.62 on VIF #0
Feb 04 17:46:52 UDM-SE udm-iptvd[97216]: Joining group 239.73.192.62 on interface iptv
Feb 04 17:46:52 UDM-SE udm-iptvd[97216]: can't join group 239.73.192.62 on interface iptv; Errno(105): No buffer space available
Feb 04 17:46:52 UDM-SE udm-iptvd[97216]: Maximum number of multicast groups were exceeded
Feb 04 17:46:52 UDM-SE udm-iptvd[97216]: Check settings of '/sbin/sysctl net.ipv4.igmp_max_memberships'
Feb 04 17:46:53 UDM-SE udm-iptvd[97216]: Route activation request from 10.214.85.183 for 233.89.188.1 is from myself. Ignoring.
Feb 04 17:46:54 UDM-SE udm-iptvd[97216]: The IGMP message was local multicast. Ignoring.
Feb 04 17:46:56 UDM-SE udm-iptvd[97216]: RECV Membership query   from 10.60.147.38    to 224.0.0.1

### Describe the Bug

After a while (10 to 20m) the tv stream is interrupted for a couple of seconds and restores. A few minutes later it completely stops. KPN shows errorcode: stb-nmc-400. 
After a minute of two the stream works ago and the issue repeats itself after 10 to 20 min

### Expected Behavior

Stable TV stream

**Comment by fabianishere** [comment]
Try switching to improxy as IGMP Proxy implementation to see if it fixes your issues.
