### ISSUE TITLE
install.sh not on latest (3.0.1) version

### ISSUE THREAD

**Issue by cinadr** [fabianishere/udm-iptv#230]
### Diagnostic Information

None as not relevant.

### Describe the Bug

While running install.sh it does not pull 3.0.1 version, only 3.0.0.

### Expected Behavior

Expected to install latest version (3.0.1).

Thanks.

**Comment by fabianishere** [comment]
Fixed with 474d93f

**Comment by cinadr** [comment]
That was quick!
Thanks.
