### ISSUE TITLE
Persistent folder moved

### ISSUE THREAD

**Issue by aafvstam** [fabianishere/udm-iptv#237]
### Diagnostic Information

n/a

### Describe the Bug

Readme.md contains:

# Copy to persistent storage
cp /etc/udm-iptv.conf /mnt/persistent/udm-iptv.conf
# Copy from persistent storage
cp /mnt/persistent/udm-iptv.conf /etc/udm-iptv.conf

The persistent folder appears to have been moved in update UDM Pro 2.4.27
So the above commands will fail.

I found the persistent folder a level lower, no longer in the mnt folder resulting in commands:

# Copy to persistent storage
cp /etc/udm-iptv.conf /persistent/udm-iptv.conf
# Copy from persistent storage
cp /persistent/udm-iptv.conf /etc/udm-iptv.conf

### Expected Behavior

Commands not to fail on missing folders😉

**Comment by fabianishere** [comment]
Addressed by [dfd1262](https://github.com/fabianishere/udm-iptv/commit/dfd1262cb0767c9ce4ee1e23a5784895810903eb)
