### ISSUE TITLE
Problem installing the udm-iptv package on UDM-Pro

### ISSUE THREAD

**Issue by 31Danny** [fabianishere/udm-iptv#254]
### What is your ISP? (if relevant)

KPN

### Diagnostic Information

root@UDMPRO-Danny:~# sh -c "$(curl https://raw.githubusercontent.com/fabianishere/udm-iptv/master/install.sh -sSf)"
Downloading packages...
Installing packages...
Ign:1 http://security.debian.org/ stretch/updates InRelease
Ign:2 http://security.debian.org/ stretch/updates Release
Ign:3 http://deb.debian.org/debian stretch InRelease
Ign:4 http://security.debian.org/ stretch/updates/contrib arm64 Packages
Ign:5 http://deb.debian.org/debian stretch-updates InRelease
Ign:6 http://security.debian.org/ stretch/updates/contrib all Packages
Ign:7 http://deb.debian.org/debian stretch-backports InRelease
Ign:8 http://security.debian.org/ stretch/updates/non-free all Packages
Ign:9 http://deb.debian.org/debian stretch Release
Ign:10 http://security.debian.org/ stretch/updates/main arm64 Packages
Ign:11 http://deb.debian.org/debian stretch-updates Release
Ign:12 http://security.debian.org/ stretch/updates/main all Packages
Ign:13 http://deb.debian.org/debian stretch-backports Release
Ign:14 http://security.debian.org/ stretch/updates/non-free arm64 Packages
Ign:15 http://deb.debian.org/debian stretch/contrib all Packages
Ign:4 http://security.debian.org/ stretch/updates/contrib arm64 Packages
Ign:16 http://deb.debian.org/debian stretch/non-free arm64 Packages
Ign:6 http://security.debian.org/ stretch/updates/contrib all Packages
Ign:17 http://deb.debian.org/debian stretch/main all Packages
Ign:8 http://security.debian.org/ stretch/updates/non-free all Packages
Ign:10 http://security.debian.org/ stretch/updates/main arm64 Packages
Ign:18 http://deb.debian.org/debian stretch/main arm64 Packages
Ign:12 http://security.debian.org/ stretch/updates/main all Packages
Ign:19 http://deb.debian.org/debian stretch/contrib arm64 Packages
Ign:14 http://security.debian.org/ stretch/updates/non-free arm64 Packages
Ign:20 http://deb.debian.org/debian stretch/non-free all Packages
Ign:4 http://security.debian.org/ stretch/updates/contrib arm64 Packages
Ign:21 http://deb.debian.org/debian stretch-updates/main arm64 Packages
Ign:6 http://security.debian.org/ stretch/updates/contrib all Packages
Ign:8 http://security.debian.org/ stretch/updates/non-free all Packages
Ign:10 http://security.debian.org/ stretch/updates/main arm64 Packages
Ign:12 http://security.debian.org/ stretch/updates/main all Packages
Ign:14 http://security.debian.org/ stretch/updates/non-free arm64 Packages
Ign:22 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:4 http://security.debian.org/ stretch/updates/contrib arm64 Packages
Ign:23 http://deb.debian.org/debian stretch-updates/contrib arm64 Packages
Ign:6 http://security.debian.org/ stretch/updates/contrib all Packages
Ign:24 http://deb.debian.org/debian stretch-updates/contrib all Packages
Ign:8 http://security.debian.org/ stretch/updates/non-free all Packages
Ign:25 http://deb.debian.org/debian stretch-updates/non-free arm64 Packages
Ign:10 http://security.debian.org/ stretch/updates/main arm64 Packages
Ign:26 http://deb.debian.org/debian stretch-updates/non-free all Packages
Ign:12 http://security.debian.org/ stretch/updates/main all Packages
Ign:27 http://deb.debian.org/debian stretch-backports/main all Packages
Ign:14 http://security.debian.org/ stretch/updates/non-free arm64 Packages
Ign:4 http://security.debian.org/ stretch/updates/contrib arm64 Packages
Ign:28 http://deb.debian.org/debian stretch-backports/main arm64 Packages
Ign:6 http://security.debian.org/ stretch/updates/contrib all Packages
Ign:15 http://deb.debian.org/debian stretch/contrib all Packages
Ign:8 http://security.debian.org/ stretch/updates/non-free all Packages
Ign:16 http://deb.debian.org/debian stretch/non-free arm64 Packages
Ign:10 http://security.debian.org/ stretch/updates/main arm64 Packages
Ign:17 http://deb.debian.org/debian stretch/main all Packages
Ign:12 http://security.debian.org/ stretch/updates/main all Packages
Ign:18 http://deb.debian.org/debian stretch/main arm64 Packages
Ign:14 http://security.debian.org/ stretch/updates/non-free arm64 Packages
Ign:19 http://deb.debian.org/debian stretch/contrib arm64 Packages
Err:4 http://security.debian.org/ stretch/updates/contrib arm64 Packages
404 Not Found [IP: 199.232.150.132 80]
Ign:6 http://security.debian.org/ stretch/updates/contrib all Packages
Ign:20 http://deb.debian.org/debian stretch/non-free all Packages
Ign:8 http://security.debian.org/ stretch/updates/non-free all Packages
Ign:10 http://security.debian.org/ stretch/updates/main arm64 Packages
Ign:21 http://deb.debian.org/debian stretch-updates/main arm64 Packages
Ign:12 http://security.debian.org/ stretch/updates/main all Packages
Ign:22 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:14 http://security.debian.org/ stretch/updates/non-free arm64 Packages
Ign:23 http://deb.debian.org/debian stretch-updates/contrib arm64 Packages
Ign:24 http://deb.debian.org/debian stretch-updates/contrib all Packages
Ign:25 http://deb.debian.org/debian stretch-updates/non-free arm64 Packages
Ign:26 http://deb.debian.org/debian stretch-updates/non-free all Packages
Ign:27 http://deb.debian.org/debian stretch-backports/main all Packages
Ign:28 http://deb.debian.org/debian stretch-backports/main arm64 Packages
Ign:15 http://deb.debian.org/debian stretch/contrib all Packages
Ign:16 http://deb.debian.org/debian stretch/non-free arm64 Packages
Ign:17 http://deb.debian.org/debian stretch/main all Packages
Ign:18 http://deb.debian.org/debian stretch/main arm64 Packages
Ign:19 http://deb.debian.org/debian stretch/contrib arm64 Packages
Ign:20 http://deb.debian.org/debian stretch/non-free all Packages
Ign:21 http://deb.debian.org/debian stretch-updates/main arm64 Packages
Ign:22 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:23 http://deb.debian.org/debian stretch-updates/contrib arm64 Packages
Ign:24 http://deb.debian.org/debian stretch-updates/contrib all Packages
Ign:25 http://deb.debian.org/debian stretch-updates/non-free arm64 Packages
Ign:26 http://deb.debian.org/debian stretch-updates/non-free all Packages
Ign:27 http://deb.debian.org/debian stretch-backports/main all Packages
Ign:28 http://deb.debian.org/debian stretch-backports/main arm64 Packages
Ign:15 http://deb.debian.org/debian stretch/contrib all Packages
Ign:16 http://deb.debian.org/debian stretch/non-free arm64 Packages
Ign:17 http://deb.debian.org/debian stretch/main all Packages
Ign:18 http://deb.debian.org/debian stretch/main arm64 Packages
Ign:19 http://deb.debian.org/debian stretch/contrib arm64 Packages
Ign:20 http://deb.debian.org/debian stretch/non-free all Packages
Ign:21 http://deb.debian.org/debian stretch-updates/main arm64 Packages
Ign:22 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:23 http://deb.debian.org/debian stretch-updates/contrib arm64 Packages
Ign:24 http://deb.debian.org/debian stretch-updates/contrib all Packages
Ign:25 http://deb.debian.org/debian stretch-updates/non-free arm64 Packages
Ign:26 http://deb.debian.org/debian stretch-updates/non-free all Packages
Ign:27 http://deb.debian.org/debian stretch-backports/main all Packages
Ign:28 http://deb.debian.org/debian stretch-backports/main arm64 Packages
Ign:15 http://deb.debian.org/debian stretch/contrib all Packages
Ign:16 http://deb.debian.org/debian stretch/non-free arm64 Packages
Ign:17 http://deb.debian.org/debian stretch/main all Packages
Ign:18 http://deb.debian.org/debian stretch/main arm64 Packages
Ign:19 http://deb.debian.org/debian stretch/contrib arm64 Packages
Ign:20 http://deb.debian.org/debian stretch/non-free all Packages
Ign:21 http://deb.debian.org/debian stretch-updates/main arm64 Packages
Ign:22 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:23 http://deb.debian.org/debian stretch-updates/contrib arm64 Packages
Ign:24 http://deb.debian.org/debian stretch-updates/contrib all Packages
Ign:25 http://deb.debian.org/debian stretch-updates/non-free arm64 Packages
Ign:26 http://deb.debian.org/debian stretch-updates/non-free all Packages
Ign:27 http://deb.debian.org/debian stretch-backports/main all Packages
Ign:28 http://deb.debian.org/debian stretch-backports/main arm64 Packages
Ign:15 http://deb.debian.org/debian stretch/contrib all Packages
Err:16 http://deb.debian.org/debian stretch/non-free arm64 Packages
404 Not Found [IP: 199.232.150.132 80]
Ign:17 http://deb.debian.org/debian stretch/main all Packages
Ign:18 http://deb.debian.org/debian stretch/main arm64 Packages
Ign:19 http://deb.debian.org/debian stretch/contrib arm64 Packages
Ign:20 http://deb.debian.org/debian stretch/non-free all Packages
Err:21 http://deb.debian.org/debian stretch-updates/main arm64 Packages
404 Not Found [IP: 199.232.150.132 80]
Ign:22 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:23 http://deb.debian.org/debian stretch-updates/contrib arm64 Packages
Ign:24 http://deb.debian.org/debian stretch-updates/contrib all Packages
Ign:25 http://deb.debian.org/debian stretch-updates/non-free arm64 Packages
Ign:26 http://deb.debian.org/debian stretch-updates/non-free all Packages
Ign:27 http://deb.debian.org/debian stretch-backports/main all Packages
Err:28 http://deb.debian.org/debian stretch-backports/main arm64 Packages
404 Not Found [IP: 199.232.150.132 80]
Hit:29 https://apt-release-candidate.artifacts.ui.com/ stretch InRelease
Hit:30 https://apt.artifacts.ui.com/ stretch InRelease
Hit:31 https://apt-beta.artifacts.ui.com/ stretch InRelease
Reading package lists...
W: The repository 'http://security.debian.org/ stretch/updates Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch-backports Release' does not have a Release file.
E: Failed to fetch http://security.debian.org/dists/stretch/updates/contrib/binary-arm64/Packages 404 Not Found [IP: 199.232.150.132 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch/non-free/binary-arm64/Packages 404 Not Found [IP: 199.232.150.132 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-arm64/Packages 404 Not Found [IP: 199.232.150.132 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch-backports/main/binary-arm64/Packages 404 Not Found [IP: 199.232.150.132 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

### Describe the Bug

404 Not Found replies

### Expected Behavior

Complete installation without failed downloads

**Comment by mrnick1234567** [comment]
If it helps I had the same issue today when installing on a UDM Pro that was just updated to 2.5.17.  

It's the `atp-get update` line in the install.sh the that gives the errors.

I got around it by running the curl commands from install.sh manually (substituting the variables with the versions in the script). This gave me the 2 .deb files, that I was able to install with apt-get install.

**Comment by 31Danny** [comment]
Thanks for your comment mrnick1234567,

Unfortunately I lack enough experience to understand in detail the manual steps you undertook to solve this.
I too had this issue just after upgrading to UniFi OS UDM Pro 2.5.17

**Comment by mrnick1234567** [comment]
OK here are the commands I used. 

ssh to your UDM

change to the temp directory
`cd /tmp`

get the packages for udm and  igmpproxy
`curl -sS -o "udm-iptv.deb" -L "https://github.com/fabianishere/udm-iptv/releases/download/v3.0.1/udm-iptv_3.0.1_all.deb"`
`curl -sS -o "igmpproxy.deb" -L "http://ftp.debian.org/debian/pool/main/i/igmpproxy/igmpproxy_0.3-1_arm64.deb"`

change permissions on the packages
`chown _apt:root igmpproxy.deb` 
`chown _apt:root udm-iptv.deb`

Install the packages
`apt-get install -y igmpproxy.deb` 
`apt-get install -y udm-iptv.deb`

This should start the setup wizard. After entering the various settings in the wizard it started working for me.

**Comment by 31Danny** [comment]
Thanks for taking the time to help me out.
Unfortunately the manual steps did not solve my issue.
The curl steps did not seem to download anything nore did they result in an error message.





Firmware version: v2.5.17

  ___ ___      .__________.__
 |   |   |____ |__\_  ____/__|
 |   |   /    \|  ||  __) |  |   (c) 2010-2022
 |   |  |   |  \  ||  \   |  |   Ubiquiti Inc.
 |______|___|  /__||__/   |__|
            |_/                  https://www.ui.com

      Welcome to UniFi Dream Machine Pro!

********************************* NOTICE **********************************
* By logging in to, accessing, or using any Ubiquiti product, you are     *
* signifying that you have read our Terms of Service (ToS) and End User   *
* License Agreement (EULA), understand their terms, and agree to be       *
* fully bound to them. The use of CLI (Command Line Interface) can        *
* potentially harm Ubiquiti devices and result in lost access to them and *
* their data. By proceeding, you acknowledge that the use of CLI to       *
* modify device(s) outside of their normal operational scope, or in any   *
* manner inconsistent with the ToS or EULA, will permanently and          *
* irrevocably void any applicable warranty.                               *
***************************************************************************

Last login: Thu Apr 27 20:44:12 2023
root@UDMPRO-Danny:~# cd /tmp
root@UDMPRO-Danny:/tmp# curl -sS -o "udm-iptv.deb" -L "https://github.com/fabianishere/udm-iptv/releases/download/v3.0.1/udm-iptv_3.0.1_all.deb"
root@UDMPRO-Danny:/tmp# curl -sS -o "igmpproxy.deb" -L "http://ftp.debian.org/debian/pool/main/i/igmpproxy/igmpproxy_0.3-1_arm64.deb"
root@UDMPRO-Danny:/tmp# chown _apt:root igmpproxy.deb
root@UDMPRO-Danny:/tmp# chown _apt:root udm-iptv.deb
root@UDMPRO-Danny:/tmp# apt-get install -y igmpproxy.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package igmpproxy.deb
E: Couldn't find any package by glob 'igmpproxy.deb'
E: Couldn't find any package by regex 'igmpproxy.deb'
root@UDMPRO-Danny:/tmp# apt-get install -y udm-iptv.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package udm-iptv.deb
E: Couldn't find any package by glob 'udm-iptv.deb'
E: Couldn't find any package by regex 'udm-iptv.deb'
root@UDMPRO-Danny:/tmp#

**Comment by mrnick1234567** [comment]
Whoops, my mistake, try:

`apt-get install -y /tmp/igmpproxy.deb`
`apt-get install -y /tmp/udm-iptv.deb`

**Comment by 31Danny** [comment]
Thank you! It's working again.
