### ISSUE TITLE
Install on UDR 3.1.11 fails

### ISSUE THREAD

**Issue by Calimerorulez** [fabianishere/udm-iptv#259]
### Diagnostic Information

Trying to install on an UDR running on 3.1.11 fails:

```
root@UDR:~# sh -c "$(curl https://raw.githubusercontent.com/fabianishere/udm-iptv/master/install.sh -sSf)"
Downloading packages...
Installing packages...
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye-backports InRelease [49.0 kB]
Err:5 https://apt-release-candidate.artifacts.ui.com bullseye InRelease
  401   [IP: 54.190.16.34 443]
Err:6 https://apt-beta.artifacts.ui.com bullseye InRelease
  401   [IP: 54.190.16.34 443]
Hit:7 https://apt.artifacts.ui.com bullseye InRelease
Reading package lists...
E: Failed to fetch https://apt-release-candidate.artifacts.ui.com/dists/bullseye/InRelease  401   [IP: 54.190.16.34 443]
E: The repository 'https://apt-release-candidate.artifacts.ui.com bullseye InRelease' is no longer signed.
E: Failed to fetch https://apt-beta.artifacts.ui.com/dists/bullseye/InRelease  401   [IP: 54.190
```.16.34 443]
E: The repository 'https://apt-beta.artifacts.ui.com bullseye InRelease' is no longer signed.


### Describe the Bug

Please see above.

### Expected Behavior

A working install ;)

**Comment by Kriskros1995** [comment]
Also issue after updating to the latest version:

Err:11 http://deb.debian.org/debian stretch/main arm64 Packages
  404  Not Found [IP: 199.232.150.132 80]
Ign:12 http://deb.debian.org/debian stretch/main all Packages
Err:13 http://deb.debian.org/debian stretch-updates/main arm64 Packages
  404  Not Found [IP: 199.232.150.132 80]
Ign:14 http://deb.debian.org/debian stretch-updates/main all Packages
Err:15 http://deb.debian.org/debian stretch-backports/main arm64 Packages
  404  Not Found [IP: 199.232.150.132 80]
Ign:16 http://deb.debian.org/debian stretch-backports/main all Packages
Hit:18 https://apt-beta.artifacts.ui.com stretch InRelease
Hit:19 https://apt.artifacts.ui.com stretch InRelease
Hit:20 https://apt-release-candidate.artifacts.ui.com stretch InRelease
Reading package lists...
W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch-backports Release' does not have a Release file.
E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-arm64/Packages  404  Not Found [IP: 199.232.150.132 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-arm64/Packages  404  Not Found [IP: 199.232.150.132 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-arm64/Packages  404  Not Found [IP: 199.232.150.132 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch-backports/main/binary-arm64/Packages  404  Not Found [IP: 199.232.150.132 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by fabianishere** [comment]
Please try to run the install script again. I've made the update step best-effort, so installation should proceed even if `apt-get update` fails.

**Comment by Calimerorulez** [comment]
Works for me now. Thanks.

**Comment by Kriskros1995** [comment]
@fabianishere It still doesn't work for me.
 
Downloading packages...
Installing packages...
Ign:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://security.debian.org/debian-security stretch/updates Release
Ign:3 http://deb.debian.org/debian stretch InRelease
Ign:4 http://deb.debian.org/debian stretch-updates InRelease
Ign:5 http://security.debian.org/debian-security stretch/updates/main arm64 Packages
Ign:6 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:7 http://deb.debian.org/debian stretch-backports InRelease
Ign:5 http://security.debian.org/debian-security stretch/updates/main arm64 Packages
Ign:8 http://deb.debian.org/debian stretch Release
Ign:9 http://deb.debian.org/debian stretch-updates Release
Ign:6 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:10 http://deb.debian.org/debian stretch-backports Release
Ign:5 http://security.debian.org/debian-security stretch/updates/main arm64 Packages
Ign:11 http://deb.debian.org/debian stretch/main arm64 Packages
Ign:6 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:5 http://security.debian.org/debian-security stretch/updates/main arm64 Packages
Ign:12 http://deb.debian.org/debian stretch/main all Packages
Ign:6 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:13 http://deb.debian.org/debian stretch-updates/main arm64 Packages
Ign:5 http://security.debian.org/debian-security stretch/updates/main arm64 Packages
Ign:14 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:6 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:15 http://deb.debian.org/debian stretch-backports/main arm64 Packages
Err:5 http://security.debian.org/debian-security stretch/updates/main arm64 Packages
  404  Not Found [IP: 199.232.150.132 80]
Ign:16 http://deb.debian.org/debian stretch-backports/main all Packages
Ign:6 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:11 http://deb.debian.org/debian stretch/main arm64 Packages
Ign:12 http://deb.debian.org/debian stretch/main all Packages
Ign:13 http://deb.debian.org/debian stretch-updates/main arm64 Packages
Ign:14 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:15 http://deb.debian.org/debian stretch-backports/main arm64 Packages
Hit:17 https://deb.nodesource.com/node_8.x stretch InRelease
Ign:16 http://deb.debian.org/debian stretch-backports/main all Packages
Ign:11 http://deb.debian.org/debian stretch/main arm64 Packages
Ign:12 http://deb.debian.org/debian stretch/main all Packages
Ign:13 http://deb.debian.org/debian stretch-updates/main arm64 Packages
Ign:14 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:15 http://deb.debian.org/debian stretch-backports/main arm64 Packages
Ign:16 http://deb.debian.org/debian stretch-backports/main all Packages
Ign:11 http://deb.debian.org/debian stretch/main arm64 Packages
Ign:12 http://deb.debian.org/debian stretch/main all Packages
Ign:13 http://deb.debian.org/debian stretch-updates/main arm64 Packages
Ign:14 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:15 http://deb.debian.org/debian stretch-backports/main arm64 Packages
Ign:16 http://deb.debian.org/debian stretch-backports/main all Packages
Ign:11 http://deb.debian.org/debian stretch/main arm64 Packages
Ign:12 http://deb.debian.org/debian stretch/main all Packages
Ign:13 http://deb.debian.org/debian stretch-updates/main arm64 Packages
Ign:14 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:15 http://deb.debian.org/debian stretch-backports/main arm64 Packages
Ign:16 http://deb.debian.org/debian stretch-backports/main all Packages
Err:11 http://deb.debian.org/debian stretch/main arm64 Packages
  404  Not Found [IP: 199.232.150.132 80]
Ign:12 http://deb.debian.org/debian stretch/main all Packages
Err:13 http://deb.debian.org/debian stretch-updates/main arm64 Packages
  404  Not Found [IP: 199.232.150.132 80]
Ign:14 http://deb.debian.org/debian stretch-updates/main all Packages
Err:15 http://deb.debian.org/debian stretch-backports/main arm64 Packages
  404  Not Found [IP: 199.232.150.132 80]
Ign:16 http://deb.debian.org/debian stretch-backports/main all Packages
Hit:18 https://apt-beta.artifacts.ui.com stretch InRelease
Hit:19 https://apt-release-candidate.artifacts.ui.com stretch InRelease
Hit:20 https://apt.artifacts.ui.com stretch InRelease
Reading package lists...
W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch-backports Release' does not have a Release file.
E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-arm64/Packages  404  Not Found [IP: 199.232.150.132 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-arm64/Packages  404  Not Found [IP: 199.232.150.132 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-arm64/Packages  404  Not Found [IP: 199.232.150.132 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch-backports/main/binary-arm64/Packages  404  Not Found [IP: 199.232.150.132 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
dialog is already the newest version (1.3-20160828-2).
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
igmpproxy is already the newest version (0.3-1).
igmpproxy set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 udm-iptv : Depends: iproute2 but it is not installable
E: Unable to correct problems, you have held broken packages.
root@ubnt:/# ^C
root@ubnt:/# sh -c "$(curl https://raw.githubusercontent.com/fabianishere/udm-iptv/master/install.sh -sSf)"
Downloading packages...
Installing packages...
Ign:1 http://deb.debian.org/debian stretch InRelease
Ign:2 http://security.debian.org/debian-security stretch/updates InRelease
Ign:3 http://deb.debian.org/debian stretch-updates InRelease
Ign:4 http://security.debian.org/debian-security stretch/updates Release
Ign:5 http://deb.debian.org/debian stretch-backports InRelease
Ign:6 http://deb.debian.org/debian stretch Release
Ign:7 http://deb.debian.org/debian stretch-updates Release
Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:9 http://deb.debian.org/debian stretch-backports Release
Ign:10 http://security.debian.org/debian-security stretch/updates/main arm64 Packages
Ign:11 http://deb.debian.org/debian stretch/main arm64 Packages
Ign:12 http://deb.debian.org/debian stretch/main all Packages
Ign:13 http://deb.debian.org/debian stretch-updates/main arm64 Packages
Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:14 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:10 http://security.debian.org/debian-security stretch/updates/main arm64 Packages
Ign:15 http://deb.debian.org/debian stretch-backports/main arm64 Packages
Ign:16 http://deb.debian.org/debian stretch-backports/main all Packages
Ign:11 http://deb.debian.org/debian stretch/main arm64 Packages
Ign:12 http://deb.debian.org/debian stretch/main all Packages
Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:13 http://deb.debian.org/debian stretch-updates/main arm64 Packages
Ign:10 http://security.debian.org/debian-security stretch/updates/main arm64 Packages
Ign:14 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:15 http://deb.debian.org/debian stretch-backports/main arm64 Packages
Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:16 http://deb.debian.org/debian stretch-backports/main all Packages
Ign:11 http://deb.debian.org/debian stretch/main arm64 Packages
Ign:12 http://deb.debian.org/debian stretch/main all Packages
Ign:10 http://security.debian.org/debian-security stretch/updates/main arm64 Packages
Ign:13 http://deb.debian.org/debian stretch-updates/main arm64 Packages
Ign:14 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:15 http://deb.debian.org/debian stretch-backports/main arm64 Packages
Ign:16 http://deb.debian.org/debian stretch-backports/main all Packages
Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:11 http://deb.debian.org/debian stretch/main arm64 Packages
Ign:10 http://security.debian.org/debian-security stretch/updates/main arm64 Packages
Ign:12 http://deb.debian.org/debian stretch/main all Packages
Ign:13 http://deb.debian.org/debian stretch-updates/main arm64 Packages
Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:14 http://deb.debian.org/debian stretch-updates/main all Packages
Err:10 http://security.debian.org/debian-security stretch/updates/main arm64 Packages
  404  Not Found [IP: 199.232.150.132 80]
Ign:15 http://deb.debian.org/debian stretch-backports/main arm64 Packages
Ign:16 http://deb.debian.org/debian stretch-backports/main all Packages
Ign:11 http://deb.debian.org/debian stretch/main arm64 Packages
Ign:12 http://deb.debian.org/debian stretch/main all Packages
Ign:13 http://deb.debian.org/debian stretch-updates/main arm64 Packages
Ign:14 http://deb.debian.org/debian stretch-updates/main all Packages
Hit:17 https://deb.nodesource.com/node_8.x stretch InRelease
Ign:15 http://deb.debian.org/debian stretch-backports/main arm64 Packages
Ign:16 http://deb.debian.org/debian stretch-backports/main all Packages
Err:11 http://deb.debian.org/debian stretch/main arm64 Packages
  404  Not Found [IP: 199.232.150.132 80]
Ign:12 http://deb.debian.org/debian stretch/main all Packages
Err:13 http://deb.debian.org/debian stretch-updates/main arm64 Packages
  404  Not Found [IP: 199.232.150.132 80]
Ign:14 http://deb.debian.org/debian stretch-updates/main all Packages
Err:15 http://deb.debian.org/debian stretch-backports/main arm64 Packages
  404  Not Found [IP: 199.232.150.132 80]
Ign:16 http://deb.debian.org/debian stretch-backports/main all Packages
Hit:18 https://apt.artifacts.ui.com stretch InRelease
Hit:19 https://apt-beta.artifacts.ui.com stretch InRelease
Hit:20 https://apt-release-candidate.artifacts.ui.com stretch InRelease
Reading package lists...
W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch-backports Release' does not have a Release file.
E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-arm64/Packages  404  Not Found [IP: 199.232.150.132 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-arm64/Packages  404  Not Found [IP: 199.232.150.132 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-arm64/Packages  404  Not Found [IP: 199.232.150.132 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch-backports/main/binary-arm64/Packages  404  Not Found [IP: 199.232.150.132 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
dialog is already the newest version (1.3-20160828-2).
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
igmpproxy is already the newest version (0.3-1).
igmpproxy set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 udm-iptv : Depends: iproute2 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by fabianishere** [comment]
It looks like your Debian installation is broken. I recommend reinstalling the UDR firmware to fix this, this is not something I can fix during installation.
