### ISSUE TITLE
KPN IPTV Error 563

### ISSUE THREAD

**Issue by Sjeff** [fabianishere/udm-iptv#276]
### What is your ISP? (if relevant)

KPN

### Diagnostic Information

Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth8
WAN VLAN: 4 (dev iptv)
WAN DHCP: true (options "-O staticroutes -V IPTV_RG")
WAN Ranges: 213.75.0.0/16  217.166.0.0/16
LAN Interfaces: br4
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: false
=== IP Link and Route ===
Device "iptv" does not exist.
Cannot find device "iptv"
=== Service Logs ===
-- Journal begins at Wed 2023-09-06 20:47:46 CEST, ends at Wed 2023-09-13 10:58:02 CEST. --
Sep 13 09:36:38 DreamMachinePro systemd[1]: udm-iptv.service: Main process exited, code=killed, status=9/KILL
Sep 13 09:36:39 DreamMachinePro systemd[1]: udm-iptv.service: Failed with result 'signal'.
Sep 13 09:36:39 DreamMachinePro systemd[1]: udm-iptv.service: Consumed 1min 12.469s CPU time.
Sep 13 09:36:39 DreamMachinePro systemd[1]: Stopped IPTV support for the UniFi Dream Machine.
Sep 13 09:36:39 DreamMachinePro systemd[1]: udm-iptv.service: Consumed 1min 12.469s CPU time.

### Describe the Bug

Failed to preset unit: Unit file /etc/systemd/system/udm-iptv.service is masked.
/usr/bin/deb-systemd-helper: error: systemctl preset failed on udm-iptv.service: No such file or directory
udm-iptv.service is a disabled or a static unit not running, not starting it.

### Expected Behavior

IPTV working after updating udm pro firmware and reinstalling udm-iptv

**Comment by SSA-NL** [comment]
I'm having the same problem.

It's my first UDM SE and after unboxing and installing it updated to 3.1.16. 
Following the script and enabling the IGMP and IPTV setting I'm getting the same error.

Downgrading to 3.1.15, I was able to get KPN iTV working.

**Comment by Sjeff** [comment]
Just got it working again.
Had some other issues where i received the log message : We couldn't apply the gateway configuration changes.

Created a backup, factory reset UDM Pro, restored backup and installed udm-iptv again.
UDM Pro firmware 3.1.16 and Network 7.5.174
