### ISSUE TITLE
Wan port is incorrect

### ISSUE THREAD

**Issue by dmouwes** [fabianishere/udm-iptv#280]
### What is your ISP? (if relevant)

KPN/XS4ALL

### Diagnostic Information

=== Configuration ===
WAN Interface: eth8
WAN VLAN: 4 (dev iptv)
WAN DHCP: true (options "-O staticroutes -V IPTV_RG")
WAN Ranges: 213.75.0.0/16  217.166.0.0/16
LAN Interfaces: br0
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
37: iptv@eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP                                                                                                                                                              group default qlen 1000
    inet 10.223.156.162/22 brd 10.223.159.255 scope global iptv
       valid_lft forever preferred_lft forever
10.223.156.0/22 proto kernel scope link src 10.223.156.162
213.75.112.0/21 via 10.223.156.1 metric 237
=== Service Logs ===
Oct 18 03:17:25 Else-Mauhsstraat udm-iptvd[426117]: Updated route entry for 224.                                                                                                                                                             0.1.187 on VIF #0
Oct 18 03:17:25 Else-Mauhsstraat udm-iptvd[426117]: RECV V2 member report   from                                                                                                                                                              192.168.1.237   to 239.255.255.251
Oct 18 03:17:25 Else-Mauhsstraat udm-iptvd[426117]: Updated route entry for 239.                                                                                                                                                             255.255.251 on VIF #0
Oct 18 03:17:26 Else-Mauhsstraat udm-iptvd[426117]: RECV V2 member report   from                                                                                                                                                              192.168.1.229   to 239.255.255.251
Oct 18 03:17:26 Else-Mauhsstraat udm-iptvd[426117]: Updated route entry for 239.                                                                                                                                                             255.255.251 on VIF #0
Oct 18 03:17:26 Else-Mauhsstraat udm-iptvd[426117]: The IGMP message was local m                                                                                                                                                             ulticast. Ignoring.
Oct 18 03:17:26 Else-Mauhsstraat udm-iptvd[426117]: The IGMP message was local m                                                                                                                                                             ulticast. Ignoring.
Oct 18 03:17:26 Else-Mauhsstraat udm-iptvd[426117]: The IGMP message was local m                                                                                                                                                             ulticast. Ignoring.
Oct 18 03:17:26 Else-Mauhsstraat udm-iptvd[426117]: The IGMP message was local m                                                                                                                                                             ulticast. Ignoring.
Oct 18 03:17:26 Else-Mauhsstraat udm-iptvd[426117]: The source address 192.168.1                                                                                                                                                             .229 for group 239.255.255.251 is from downstream VIF[0]. Ignoring.
root@Else-Mauhsstraat:~# === Configuration ===
WAN Interface: eth8
WAN VLAN: 4 (dev iptv)
WAN DHCP: true (options "-O staticroutes -V IPTV_RG")
WAN Ranges: 213.75.0.0/16  217.166.0.0/16
LAN Interfaces: br0
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
37: iptv@eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP                                                                                                                                                              group default qlen 1000
    inet 10.223.156.162/22 brd 10.223.159.255 scope global iptv
       valid_lft forever preferred_lft forever
10.223.156.0/22 proto kernel scope link src 10.223.156.162
213.75.112.0/21 via 10.223.156.1 metric 237
=== Service Logs ===
Oct 18 03:17:25 Else-Mauhsstraat udm-iptvd[426117]: Updated route entry for 224.                                                                                                                                                             0.1.187 on VIF #0
Oct 18 03:17:25 Else-Mauhsstraat udm-iptvd[426117]: RECV V2 member report   from                                                                                                                                                              192.168.1.237   to 239.255.255.251
Oct 18 03:17:25 Else-Mauhsstraat udm-iptvd[426117]: Updated route entry for 239.                                                                                                                                                             255.255.251 on VIF #0
Oct 18 03:17:26 Else-Mauhsstraat udm-iptvd[426117]: RECV V2 member report   from                                                                                                                                                              192.168.1.229   to 239.255.255.251
Oct 18 03:17:26 Else-Mauhsstraat udm-iptvd[426117]: Updated route entry for 239.                                                                                                                                                             255.255.251 on VIF #0
Oct 18 03:17:26 Else-Mauhsstraat udm-iptvd[426117]: The IGMP message was local m                                                                                                                                                             ulticast. Ignoring.
Oct 18 03:17:26 Else-Mauhsstraat udm-iptvd[426117]: The IGMP message was local m                                                                                                                                                             ulticast. Ignoring.
Oct 18 03:17:26 Else-Mauhsstraat udm-iptvd[426117]: The IGMP message was local m                                                                                                                                                             ulticast. Ignoring.
Oct 18 03:17:26 Else-Mauhsstraat udm-iptvd[426117]: The IGMP message was local m                                                                                                                                                             ulticast. Ignoring.
Oct 18 03:17:26 Else-Mauhsstraat udm-iptvd[426117]: The source address 192.168.1                                                                                                                                                             .229 for group 239.255.255.251 is from downstream VIF[0]. Ignoring.

### Describe the Bug

In the above it says the WAN interface is port 8, but it's port 9 on the UDM pro. I guess this is why IPTV isn't working.

### Expected Behavior

I expected the script to link it to port 9 and not port 8

**Comment by drecomx** [comment]
Linux starts with eth0. So, eth8 is port 9

**Comment by fabianishere** [comment]
@drecomx is correct. Are you sure the STB is connected to the correct VLAN?
