### ISSUE TITLE
Modules can't load in UDM SE 3.2.5

### ISSUE THREAD

**Issue by viriatusX** [fabianishere/udm-iptv#282]
### Diagnostic Information

The modules cannot load anymore since UDM SE 3.2.5

### Describe the Bug

Hi @fabianishere , 

There is a problem. With the recent update of UDM SE 3.2.5 it seems that loading compiled modules is no longer allowed like: [https://gathering.tweakers.net/forum/list_messages/1883441?data%5Bfilter_keywords%5D=rtsp](url). 
It shows the following error:

**modprobe: ERROR: could not insert 'nf_nat_rtsp': Required key not available**

### Expected Behavior

Not work anymore

**Comment by hhuitema** [comment]
Do you still have a problem with release 3.2.6 ?
for now i am sticking to the 3.1 branch.. Having a 'Wife Acceptance Factor' to take into account.

**Comment by viriatusX** [comment]
> Do you still have a problem with release 3.2.6 ? for now i am sticking to the 3.1 branch.. Having a 'Wife Acceptance Factor' to take into account.

Yes..... :(

**Comment by alexhk90** [comment]
Also not working for me now on UDM with UniFi OS v3.2.7, which I guess is probably the same issue. 

"udm-iptv diagnose" output:
```
Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth4
WAN VLAN: 0 (dev iptv)
WAN DHCP: false (options "-O staticroutes -V IPTV_RG")
WAN Static IP: 10.20.30.1/24
WAN Ranges: 224.0.0.0/4  109.159.247.0/24
LAN Interfaces: br40
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
4: eth4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 10.20.30.1/24 scope global eth4
       valid_lft forever preferred_lft forever
10.20.30.0/24 proto kernel scope link src 10.20.30.1 
=== Service Logs ===
Dec 16 10:38:27 UDM01 udm-iptvd[582752]: DEBUG[main@655]: timeout
Dec 16 10:38:27 UDM01 udm-iptvd[582752]: DEBUG[main@655]: timeout
Dec 16 10:38:27 UDM01 udm-iptvd[582752]: DEBUG[main@655]: timeout
Dec 16 10:38:27 UDM01 udm-iptvd[582752]: DEBUG[main@655]: timeout
Dec 16 10:38:27 UDM01 udm-iptvd[582752]: DEBUG[main@655]: timeout
Dec 16 10:38:27 UDM01 udm-iptvd[582752]: DEBUG[main@655]: timeout
Dec 16 10:38:27 UDM01 udm-iptvd[582752]: DEBUG[main@655]: timeout
Dec 16 10:38:27 UDM01 udm-iptvd[582752]: DEBUG[main@655]: timeout
Dec 16 10:38:27 UDM01 udm-iptvd[582752]: DEBUG[main@655]: timeout
Dec 16 10:38:27 UDM01 udm-iptvd[582752]: DEBUG[main@655]: timeout
```

It was working well before upgrading UniFi OS (I think the previous version was v3.1.6, or at least v3.1.x).

**Comment by alexhk90** [comment]
Might be a different issue, but working for me now on UDM with UniFi OS v3.2.7, by (re-)running "udm-iptv configure" and choosing "IGMPv2" (instead of "IGMPv3").

**Comment by fabianishere** [comment]
Hey @viriatusX, those `nf_nat_rtsp` modules are not something supported by this project. My suggestion would be to further inquire on Tweakers.
