### ISSUE TITLE
After update to OS v3.2.7 KPN-IPTV not working anymore

### ISSUE THREAD

**Issue by john1469** [fabianishere/udm-iptv#290]
### What is your ISP? (if relevant)

KPN

### Diagnostic Information

=== Configuration ===
WAN Interface: eth8
WAN VLAN: 4 (dev iptv)
WAN DHCP: true (options "-O staticroutes -V IPTV_RG")
WAN Ranges: 213.75.0.0/16  217.166.0.0/16
LAN Interfaces: br4
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
=== Service Logs ===
Dec 10 21:02:37 UDM-6446 udm-iptvd[673391]: DEBUG[init_interface@208]: if_mtu = 1500
Dec 10 21:02:37 UDM-6446 udm-iptvd[673391]: DEBUG[init_interface@214]: if_falgs = 4163
Dec 10 21:02:37 UDM-6446 udm-iptvd[673391]: DEBUG[init_interface@178]: iptv's ipv4 address is 10.119.99.249
Dec 10 21:02:37 UDM-6446 udm-iptvd[673391]: DEBUG[init_interface@195]: if_index = 412
Dec 10 21:02:37 UDM-6446 udm-iptvd[673391]: DEBUG[init_interface@208]: if_mtu = 1500
Dec 10 21:02:37 UDM-6446 udm-iptvd[673391]: DEBUG[init_interface@214]: if_falgs = 4163
Dec 10 21:02:37 UDM-6446 udm-iptvd[673391]: ERROR[main@619]: exiting.........
Dec 10 21:02:37 UDM-6446 IMPROXY[673391]: ERROR[main@619]: exiting.........
Dec 10 21:02:37 UDM-6446 systemd[1]: udm-iptv.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 21:02:37 UDM-6446 systemd[1]: udm-iptv.service: Failed with result 'exit-code'.

### Describe the Bug

After an update to OS v3.2.7 I am not able to get IPTV working again.
I have ran the script again, but without success.
I have uninstalled the udm-iptv, rebooted and again installed, without success.

### Expected Behavior

What could be the root-cause of this issue?

**Comment by alexhk90** [comment]
Also not working for me after upgrading to UniFi OS v3.2.7 - seems to be since v3.2 (see #282).

**Comment by john1469** [comment]
Alex, 
After the upgrade I had IGPM Proxy enabled. 
After switching off, everything was working. 

John

**Comment by alexhk90** [comment]
Thanks, John! 

IGMP Proxy wasn't enabled for me, but it did prompt me to check and I managed to fix it by running "udm-iptv configure" and choosing "IGMPv2" (instead of "IGMPv3").

**Comment by arjen-w** [comment]
I can confirm it is working on version 3.2.7, for me also with using IGMPv2 instead of using v3.

**Comment by rsterrenburg** [comment]
Worked for me too after reinstalling the script

**Comment by peterfortuin** [comment]
I installed version 3.2.9 on my UDM today and everything worked fine. Also with IGMPv3.

**Comment by Spor36** [comment]
Hi all, I had an internet problem, upgraded to v3.2.7 and wanted to install the script again. Now I cannot get into unifi-os with this code: unifi-os shell?

I do read you get it working again, how do you guys do that?

**Comment by klaasnicolaas** [comment]
I also had a lot of problems with OS v3.2.7, I had to install the igmpproxy package separately. After the update to OS v3.2.9 everything works smoothly even without reinstalling the udm-igmp package 🤔
