### ISSUE TITLE
Issues with IPTV buffering

### ISSUE THREAD

**Issue by VeggieData** [fabianishere/udm-iptv#3]
I was wondering if anyone else has seen any issues since updating to the 1.11.16 UDM firmware? I've suddenly come into an issue with buffering on my IPTV streams, which seems to happen every minute or so,

I've been through all settings and have downgraded and upgraded firmware, but nothing seems to resolve it. There are no other issues with any other streaming services or any application on  my local network. I've even taken it all back to just my UDM and IPTV connected and while that works fine for a while, the issue eventually comes back.

IPTV traffic is on a separate VLAN to all other devices, and the the IPTV receiver goes directly into my UDM, so no other switches or devices are involved in routing the traffic. I've put in FW rules to prevent IPTV traffic from hitting the LAN and vice versa.

I cannot think of anything else to try, but i can't see it being a separate connection issue with the ISP as this is the only service impacted. Does anyone have any ideas!!!

**Comment by olafnorge** [comment]
I experience the same. I am running on `1.11.0-20` but I also saw it at `1.10.4` and `1.11.0-16`. My ISP is German Telekom. When I put a pfSense w/ igmproxy in between and connect the Magenta device via a switch directly to it I don't have any issues w/ buffering.

**Comment by fabianishere** [comment]
@olafnorge Is your IPTV traffic also on a separate VLAN?

**Comment by olafnorge** [comment]
No, MagentaTV of German Telekom runs on the same VLAN as the "main" connection. I am on FTTH, have a fiber modem and do PPoE through the UDMP and tag the connection w/ VLAN 7 - when I am NOT using the pfSense. My IPTV device is on a dedicated subnet with it's own VLAN.

With the pfSense in between the pfSense does the PPoE and the UDMP is not involved in the IPTV traffic at all. It runs stable, but w/ this setup I do have other issues like double NAT and all the other things that come w/ such a setup. :(

**Comment by fabianishere** [comment]
IGMP Snooping is also enabled on the switches and for the UniFi network?

**Comment by olafnorge** [comment]
Jep it is. There is no additional switch involved when I do the direct connection as I plug the IPTV device directly into one of the UDMP ports and set the profile of the port to the dedicated iptv vlan/network.

**Comment by VeggieData** [comment]
I'm still having this issue, and it has persisted through each release from 1.11.0-16 onwards. I've tired both separate and the same VLAN but it still seems to 'buffer' or drop the connection for a few seconds all the time. I still have no issues when using the EdgeRouter and running IGMP proxy via that, with the IPTV device directly connected.

Are there any logs that can be captured on the UDM to troubleshoot for this? The IPTV log that i run via Podman doesn't give too much useable detail or flags any obvious errors.

**Comment by fabianishere** [comment]
It might be helpful to share the debug logs of `igmpproxy` (as described [here](https://github.com/fabianishere/udm-iptv#debugging-igmp-proxy)).
Otherwise, you could try to capture a packet trace of both your internal IPTV VLAN as well as the WAN side, perhaps something interesting is happening there.

**Comment by fabianishere** [comment]
This is a stab in the dark, but could you check whether the issue persists when connecting the IPTV receiver via an intermediate switch.
This eliminates the possibility of the internal UDM(P) switch being the cause of these issues.

**Comment by VeggieData** [comment]
After a lot of messing around and moving switches it looks like i've got everything back working again. All it took was a factory reset of the UDM! I set everything up from scratch as i didn't want to restore a bad config if that was the cause, and when i configured the IGMP Proxy again it all worked. I even upgraded to 1.11.0-21 and that worked too.

I can only assume that something went wrong when i upgraded from 1.11.0-15 to -16 and that persisted through all subsequent updates.
