### ISSUE TITLE
IMPROXY generates errors on UGX-Lite

### ISSUE THREAD

**Issue by dmutsaers** [fabianishere/udm-iptv#303]
### What is your ISP? (if relevant)

KPN

### Diagnostic Information

=== Configuration ===
WAN Interface: eth1
WAN VLAN: 4 (dev iptv)
WAN DHCP: true (options "-O staticroutes -V IPTV_RG")
WAN Ranges: 213.75.0.0/16  217.166.0.0/16
LAN Interfaces: eth0.2
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: false
=== IP Link and Route ===
21: iptv@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    inet 10.15.130.30/22 brd 10.15.131.255 scope global iptv
       valid_lft forever preferred_lft forever
10.15.128.0/22 proto kernel scope link src 10.15.130.30
213.75.112.0/21 via 10.15.128.1 metric 221
=== Service Logs ===
Jan 06 11:37:53 UniFiNext-GenGatewayLite udm-iptvd[3684]: udhcpc: sending discover
Jan 06 11:37:53 UniFiNext-GenGatewayLite udm-iptvd[3684]: udhcpc: sending select for 10.15.130.30
Jan 06 11:37:53 UniFiNext-GenGatewayLite udm-iptvd[3684]: udhcpc: lease of 10.15.130.30 obtained, lease time 3600
Jan 06 11:37:54 UniFiNext-GenGatewayLite udm-iptvd[3655]: NATing IPTV network ranges (if necessary)
Jan 06 11:37:54 UniFiNext-GenGatewayLite udm-iptvd[3655]: Creating static routes (if necessary)
Jan 06 11:37:54 UniFiNext-GenGatewayLite udm-iptvd[3655]: Setting up IGMP Proxy
Jan 06 11:37:54 UniFiNext-GenGatewayLite udm-iptvd[3655]: Using improxy...
Jan 06 11:37:55 UniFiNext-GenGatewayLite udm-iptvd[3655]: Starting IGMP Proxy
_**Jan 06 11:37:55 UniFiNext-GenGatewayLite IMPROXY[3655]: ERROR[init_interface@172]: SIOCGIFADDR filed eth0
Jan 06 11:37:55 UniFiNext-GenGatewayLite udm-iptvd[3655]: init_interface: Cannot assign requested address**_

### Describe the Bug

After installing, starting and configuring udm-iptv some errors appear in the service logs (udm-iptv diagnose)

Jan 06 11:37:55 UniFiNext-GenGatewayLite IMPROXY[3655]: ERROR[init_interface@172]: SIOCGIFADDR filed eth0
Jan 06 11:37:55 UniFiNext-GenGatewayLite udm-iptvd[3655]: init_interface: Cannot assign requested address

### Expected Behavior

No errors in the service logs when running udm-iptv

**Comment by jgriffiths014** [comment]
i have a bug open for the UXG Lite and i get this when i attempt to use a vlan to route the iptv traffic to instead of br0 (in your case eth0.2). i know that doesn't really help though, sorry, but I cant get it to work for longer than 10 minutes even when using br0.

**Comment by marcoheijkoop** [comment]
This GitHub is about the UDM Pro not the UGX Lite. So maybe it's not working because off that

**Comment by dmutsaers** [comment]
@marcoheijkoop  Support for UGX Lite has been recently added...

**Comment by dmutsaers** [comment]
@jgriffiths014  I have no problems other than the one I reported above, IPTV is working without any problems on my UGX Lite. I assume this error only appears if you create VLANS on the UGX Lite. When I had only two interfaces WAN/LAN, without any vlans I didn't see this error, if I recall correctly.

**Comment by RaimondB** [comment]
@dmutsaers how did you set it up on the UXG Lite, using a Custom setup? Because it will not read the file for the KPN setup.
I have tried a custom setup, but I cannot get the connection working correctly, although I think i specified the right values. 

I do have a bunch of internal VLANs, including one for the IPTV. How can I specify which VLAN to use on the LAN side?

**Comment by jgriffiths014** [comment]
@RaimondB I'm not on KPN, but you need to specify the correct interface for your IPTV vlan via the settings file in /etc/udm-iptv.conf, i.e. mine is set to IPTV_LAN_INTERFACES="eth0.3". you can find this via the 'ifconfig' command.

**Comment by dmutsaers** [comment]
@RaimondB You can't use the tool to set the correct variables, you have to edit the udm-iptv.conf file manually.  Mine looks like this (iptv on vlan 2):
`## Example configuration for udmp-iptv ##
# Interface on which IPTV traffic enters the router
IPTV_WAN_INTERFACE="eth1"
# ID of VLAN which carries IPTV traffic (use 0 if no VLAN is used)
IPTV_WAN_VLAN="4"
# Name of the IPTV VLAN interface
IPTV_WAN_VLAN_INTERFACE="iptv"
# IP ranges from which the IPTV traffic originates (separated by spaces)
IPTV_WAN_RANGES="213.75.0.0/16  217.166.0.0/16"
# DHCP options to send when requesting an IP address
IPTV_WAN_DHCP_OPTIONS="-O staticroutes -V IPTV_RG"
# LAN interfaces on which IPTV should be made available
IPTV_LAN_INTERFACES="eth0.2"
# Disable quickleave for igmpproxy
IPTV_IGMPPROXY_DISABLE_QUICKLEAVE="false"
# Enable debugging for igmpproxy
IPTV_IGMPPROXY_DEBUG="false"
IPTV_IGMPPROXY_PROGRAM="improxy"
IPTV_IGMPPROXY_IGMP_VERSION="3"
`

**Comment by RaimondB** [comment]
Yes I modified above. It is working, however sometimes after a day or so the KPN modem reports it can't connect and then I need to reboot the settop box to make it working again. @dmutsaers have you had such issues?

**Comment by RaimondB** [comment]
Btw I do also get the mentioned error message at the start of the topic sometimes. But it is hard to pin down when it exactly happens.

**Comment by jgriffiths014** [comment]
from my experience, those errors are "normal". I get them still now and my setup works fine. What network infrastructure do you have in between the KPN modem and your IPTV box? my issue was switches that supposedly supported IGMP Snooping but actually either didn't or had a poor implementation of it. As soon as i upgraded to Unifi switches its been flawless ever since.

**Comment by dmutsaers** [comment]
> Yes I modified above. It is working, however sometimes after a day or so the KPN modem reports it can't connect and then I need to reboot the settop box to make it working again. @dmutsaers have you had such issues?

No, I have no issues beside the errors mentioned in the first post.

**Comment by RaimondB** [comment]
I am now trying igmpproxy instead of improxy. Maybe that can prevent the SIOCGIFADDR filed eth0 error.

Also, I have seen that the improxy config file will contain eth0 and eth0.4 as downstream if you configure only eth0.4 as a downstream interface. Maybe this is related to the error mentioned, since eth0 does not have an ip-address on the UXG-Lite, because that is link to br0.

**Comment by dmutsaers** [comment]
> since eth0 does not have an ip-address on the UXG-Lite, because that is link to br0.

My thoughts exactly, but I'm no expert. 😉

**Comment by RaimondB** [comment]
> However, I don't see eth0 mentioned in the config file.

I mean in the /var/run/igmpproxy.iptv.conf file. Is that the file you were also checking?

**Comment by dmutsaers** [comment]
> > However, I don't see eth0 mentioned in the config file.
> 
> I mean in the /var/run/igmpproxy.iptv.conf file. Is that the file you were also checking?

```
# improxy configuration for udm-iptv
igmp enable version 3
mld disable
upstream iptv
downstream eth0
downstream eth0.2
```

It is present...

**Comment by zoomwaffle** [comment]
`=== Configuration ===
WAN Interface: eth1
WAN VLAN: 4 (dev iptv)
WAN DHCP: true (options "-O staticroutes -V IPTV_RG")
WAN Ranges: 213.75.0.0/16  217.166.0.0/16
LAN Interfaces: eth0.212
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: false
=== IP Link and Route ===
=== Service Logs ===
Jun 10 07:57:58 UXG-Lite udm-iptvd[277210]: Using improxy...
Jun 10 07:57:58 UXG-Lite udm-iptvd[277210]: Starting IGMP Proxy
Jun 10 07:57:58 UXG-Lite IMPROXY[277210]: ERROR[init_interface@172]: SIOCGIFADDR filed eth0
Jun 10 07:57:58 UXG-Lite IMPROXY[277210]: ERROR[main@619]: exiting.........
Jun 10 07:57:58 UXG-Lite udm-iptvd[277210]: init_interface: Cannot assign requested address
Jun 10 07:57:58 UXG-Lite udm-iptvd[277210]: MRT_INIT: Address already in use
Jun 10 07:57:58 UXG-Lite udm-iptvd[277210]: ERROR[init_interface@172]: SIOCGIFADDR filed eth0
Jun 10 07:57:58 UXG-Lite udm-iptvd[277210]: ERROR[main@619]: exiting.........
Jun 10 07:57:58 UXG-Lite systemd[1]: udm-iptv.service: Main process exited, code=exited, status=1/FAILURE
Jun 10 07:57:58 UXG-Lite systemd[1]: udm-iptv.service: Failed with result 'exit-code'.`

So I've got the same issue - is this user error on my behalf causing this? Or something to be fixed? It isn't quite clear from the above.

**Comment by fabianishere** [comment]
@zoomwaffle Please make sure you have not enabled IPTV support within the UniFi UI.
