### ISSUE TITLE
Labeling of WAN ports in setup dialog

### ISSUE THREAD

**Issue by MattieGit** [fabianishere/udm-iptv#308]
### What is your ISP? (if relevant)

KPN

### Diagnostic Information

=== Configuration ===
WAN Interface: eth9
WAN VLAN: 4 (dev iptv)
WAN DHCP: true (options "-O staticroutes -V IPTV_RG")
WAN Ranges: xxx.yy..0.0/16  xxx.yyy.0.0/16
LAN Interfaces: br3
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: false
=== IP Link and Route ===
175: iptv@eth9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    inet 10.202.145.254/22 brd 10.202.147.255 scope global iptv
       valid_lft forever preferred_lft forever
10.202.144.0/22 proto kernel scope link src 10.202.145.254 
213.75.112.0/21 via 10.202.144.1 metric 375 

### Describe the Bug

WAN1 is my default WAN connection via SFP+.
WAN2 is my backup WAN (failover only), via a 4G modem

The setup dialog let's me choose between WAN1 (RJ45) and WAN2 (SFP+). I have to select WAN2, because the SFP+ is my default WAN connection. It's a bit confusing that this is labeled WAN2, while the Unifi interface calls it WAN1.
The system is working flawlessly, so rather than a bug, this is a recommendation to update the labels in the setup dialog.

<img width="561" alt="Screenshot 2024-02-20 at 20 43 48" src="https://github.com/fabianishere/udm-iptv/assets/6250046/1de94d0e-a888-4169-bbb8-4294a38e13ef">

### Expected Behavior

Show the SFP+ WAN as WAN1, instead of WAN2 to be compatible with the naming in the Unifi admin interface.

**Comment by fabianishere** [comment]
Hey @MattieGit, WAN1 for RJ45 is the default naming used by UniFi. Though, it looks like UniFi interface allows renaming the interfaces based on which one is the primary. Given the complexity of getting the actual names for the interfaces, I do not plan to fix this unfortunately.
