### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ThijmenKort** [fabianishere/udm-iptv#319]
### Diagnostic Information

root@Router:~# sh -c "$(curl https://raw.githubusercontent.com/fabianishere/udm-iptv/master/install.sh -sSf)"
Downloading packages...
Installing packages...
Reading package lists...
E: Invalid archive signature
E: Internal error, could not locate member control.tar{.zst,.lz4,.gz,.xz,.bz2,.lzma,}
E: Could not read meta data from /tmp/tmp.WzyXMmZXCQ/udm-iptv.deb
E: The package lists or status file could not be parsed or opened.

### Describe the Bug

udm-iptv.deb cannot be found

### Expected Behavior

Installation should succeed

**Comment by ThijmenKort** [comment]
Looks like UDM_IPTV_VERSION was changed in latest commit. But since there is no release that matches this version you can't install the package.

`curl -sS -o "$dest/udm-iptv.deb" -L "https://github.com/fabianishere/udm-iptv/releases/download/v$UDM_IPTV_VERSION/udm-iptv_${UDM_IPTV_VERSION}_all.deb"
`

**Comment by ThijmenKort** [comment]
@erikpost @fabianishere please read above

**Comment by fabianishere** [comment]
Should be fixed now
