### ISSUE TITLE
Failed to install package

### ISSUE THREAD

**Issue by dmouwes** [fabianishere/udm-iptv#321]
### What is your ISP? (if relevant)

KPN

### Diagnostic Information

Installing packages...
E: Failed to fetch https://apt-beta.artifacts.ui.com/dists/bullseye/InRelease  401   [IP: 52.10.249.110 443]
E: The repository 'https://apt-beta.artifacts.ui.com bullseye InRelease' is no longer signed.
E: Failed to fetch https://apt-release-candidate.artifacts.ui.com/dists/bullseye/InRelease  401   [IP: 52.10.249.110 443]
E: The repository 'https://apt-release-candidate.artifacts.ui.com bullseye InRelease' is no longer signed.
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to install dialog... Using readline frontend
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  igmpproxy
The following packages will be upgraded:
  udm-iptv
1 upgraded, 0 newly installed, 0 to remove and 44 not upgraded.
1 not fully installed or removed.
Need to get 0 B/16.5 kB of archives.
After this operation, 2048 B of additional disk space will be used.
Get:1 /tmp/tmp.20xFoScFSG/udm-iptv.deb udm-iptv all 3.0.5 [16.5 kB]
Preconfiguring packages ...
/tmp/udm-iptv.config.9MvBBN: 21: /etc/udm-iptv.conf: Syntax error: Unterminated quoted string
udm-iptv failed to preconfigure, with exit status 2
(Reading database ... 49027 files and directories currently installed.)
Preparing to unpack .../tmp.20xFoScFSG/udm-iptv.deb ...
Unpacking udm-iptv (3.0.5) over (3.0.4) ...
Setting up udm-iptv (3.0.5) ...
/var/lib/dpkg/info/udm-iptv.config: 21: /etc/udm-iptv.conf: Syntax error: Unterminated quoted string
dpkg: error processing package udm-iptv (--configure):
 installed udm-iptv package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 udm-iptv
E: Sub-process /usr/bin/dpkg returned an error code (1)

### Describe the Bug

Cloud Gateway Ultra won't install the updated script.

### Expected Behavior

installation of the script

**Comment by erikpost** [comment]
From the log it looks like the script cannot update the package repositories from Ubiquiti and fails to install required packages. Also there's one package that has not been fully installed.

What Unifi OS version are you on? And can you post the contents of the /etc/udm-iptv.conf file?

I'd suggest restarting your UCG Ultra and running the script again and posting the results.

**Comment by dmouwes** [comment]
UniFi OS 3.2.12, don't know how to get the contents of /etc/udm-iptv.conf file. I've already tried a restart and that didn't help.

**Comment by dmutsaers** [comment]
Is UniFi OS 3.2.15 not a requirement? (It was on UXG-Lite)

**Comment by dmouwes** [comment]
This is currently the latest official release, so I don't think so

**Comment by dmutsaers** [comment]
I'm mistaken, UniFi OS 3.1.16 was an early access release for the UXG-Lite and a requirement for UDM-IPTV.

**Comment by erikpost** [comment]
@dmutsaers the Gateway series has different Unifi OS releases than the Cloud Gateways. It seems 3.2.12 is the latest Official release for UCG Ultra, with 3.2.17 being released as Release candidate today.

@dmouwes how much Linux knowledge do you have? Without any it will be difficult to troubleshoot this issue or to make manual changes to the setup.

But can you try the following, type 'cat /etc/udm-iptv.conf' (without the quotes) and post the results.

Also post the log of what happens when you try a new install of the script.

And finally does 'udm-iptv reconfigure' work for you?

**Comment by dmutsaers** [comment]
> @dmutsaers the Gateway series has different Unifi OS releases than the Cloud Gateways. It seems 3.2.12 is the latest Official release for UCG Ultra, with 3.2.17 being released as Release candidate today.

I stand corrected 😉

**Comment by dmouwes** [comment]
I don't have any linux knowledge. I used the script before on an UDM and that worked fine mostly. 
The udm-iptv reconfigure does this result: /usr/sbin/dpkg-reconfigure: udm-iptv is broken or not fully installed.

This is the result of 'cat /etc/udm-iptv.conf:
## Example configuration for udmp-iptv ##
# Interface on which IPTV traffic enters the router
IPTV_WAN_INTERFACE=eth5"
# ID of VLAN which carries IPTV traffic (use 0 if no VLAN is used)
IPTV_WAN_VLAN="4"
# Name of the IPTV VLAN interface
IPTV_WAN_VLAN_INTERFACE="iptv"
# IP ranges from which the IPTV traffic originates (separated by spaces)
IPTV_WAN_RANGES="213.75.0.0/16  217.166.0.0/16"
# DHCP options to send when requesting an IP address
IPTV_WAN_DHCP_OPTIONS="-O staticroutes -V IPTV_RG"
# LAN interfaces on which IPTV should be made available
IPTV_LAN_INTERFACES="br4"
# Disable quickleave for igmpproxy
IPTV_IGMPPROXY_DISABLE_QUICKLEAVE="false"
# Enable debugging for igmpproxy
IPTV_IGMPPROXY_DEBUG="false"
IPTV_IGMPPROXY_PROGRAM="improxy"

IPTV_IGMPPROXY_IGMP_VERSION="3"

This is what happens when I install the script new: 
Downloading packages...
Installing packages...
E: Failed to fetch https://apt-beta.artifacts.ui.com/dists/bullseye/InRelease  4                                                                                                                                                             01   [IP: 52.10.249.110 443]
E: The repository 'https://apt-beta.artifacts.ui.com bullseye InRelease' is no l                                                                                                                                                             onger signed.
E: Failed to fetch https://apt-release-candidate.artifacts.ui.com/dists/bullseye                                                                                                                                                             /InRelease  401   [IP: 35.160.231.47 443]
E: The repository 'https://apt-release-candidate.artifacts.ui.com bullseye InRel                                                                                                                                                             ease' is no longer signed.
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to install dialog... Using readline frontend
Reading package lists...
Building dependency tree...
Reading state information...
udm-iptv is already the newest version (3.0.5).
0 upgraded, 0 newly installed, 0 to remove and 44 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up udm-iptv (3.0.5) ...
/var/lib/dpkg/info/udm-iptv.config: 21: /etc/udm-iptv.conf: Syntax error: Unterm                                                                                                                                                             inated quoted string
dpkg: error processing package udm-iptv (--configure):
 installed udm-iptv package post-installation script subprocess returned error e                                                                                                                                                             xit status 2
Errors were encountered while processing:
 udm-iptv
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by erikpost** [comment]
I think I see one thing that could be causing the issue. In /etc/udm-iptv.conf the setting IPTV_WAN_INTERFACE is missing a double quote. And besides for the UCG Ultra it needs to have the value `eth4` (which is the name of the default WAN port, port 5 on the device). Not sure where the `eth5` value is coming from though, the script should default to `eth8` and ask for the correct interface for your device in the setup wizard.

So it should say:
`IPTV_WAN_INTERFACE="eth4"`

You can edit this with `vi /etc/udm-iptv.conf`. Move the cursor to the line with `IPTV_WAN_INTERFACE`, and position it at the letter `e`. Press `x` several times so that everything after the `=` is deleted. The cursor should now be at the `=`. Press `a` and type `"eth4"` (include the double quotes). Make sure that the line reads `IPTV_WAN_INTERFACE="eth4"`. Press `Esc` and type `:wq` and press `Enter` to save the change and quit the text editor.

The other thing is that one package does not seem to be installed fully. After doing the above change you could try running `dpkg --configure -a` to try to fix that and report what the output of that command is.

**Comment by dmutsaers** [comment]
> @dmutsaers the Gateway series has different Unifi OS releases than the Cloud Gateways. It seems 3.2.12 is the latest Official release for UCG Ultra, with 3.2.17 being released as Release candidate today.

3.2.17 is "Official" for the Cloud Gateway Ultra

**Comment by dmouwes** [comment]
I just updated to unifi OS 3.2.17 and tried installing the script again after, this is what I got this time: sh -c "$(curl https://raw.githubusercontent.com/fabiani                                                                                                                                                             shere/udm-iptv/master/install.sh -sSf)"
Downloading packages...
Installing packages...
E: Failed to fetch https://apt-release-candidate.artifacts.ui.com/dists/bullseye                                                                                                                                                             /InRelease  401   [IP: 52.32.129.26 443]
E: The repository 'https://apt-release-candidate.artifacts.ui.com bullseye InRel                                                                                                                                                             ease' is not signed.
E: Failed to fetch https://apt-beta.artifacts.ui.com/dists/bullseye/InRelease  4                                                                                                                                                             01   [IP: 35.160.231.47 443]
E: The repository 'https://apt-beta.artifacts.ui.com bullseye InRelease' is not                                                                                                                                                              signed.
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  igmpproxy
The following NEW packages will be installed:
  udm-iptv
0 upgraded, 1 newly installed, 0 to remove and 19 not upgraded.
Need to get 0 B/16.5 kB of archives.
After this operation, 74.8 kB of additional disk space will be used.
Get:1 /tmp/tmp.4TwNAIEWbv/udm-iptv.deb udm-iptv all 3.0.5 [16.5 kB]
Preconfiguring packages ...
/tmp/udm-iptv.config.nBGPJ6: 21: /etc/udm-iptv.conf: Syntax error: Unterminated                                                                                                                                                              quoted string
udm-iptv failed to preconfigure, with exit status 2
Selecting previously unselected package udm-iptv.
(Reading database ... 49011 files and directories currently installed.)
Preparing to unpack .../tmp.4TwNAIEWbv/udm-iptv.deb ...
Unpacking udm-iptv (3.0.5) ...
Setting up udm-iptv (3.0.5) ...

Configuration file '/etc/udm-iptv.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
 ==> Keeping old config file as default.
/var/lib/dpkg/info/udm-iptv.config: 21: /etc/udm-iptv.conf: Syntax error: Unterm                                                                                                                                                             inated quoted string
dpkg: error processing package udm-iptv (--configure):
 installed udm-iptv package post-installation script subprocess returned error e                                                                                                                                                             xit status 2
Errors were encountered while processing:
 udm-iptv
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by erikpost** [comment]
@dmouwes did you try the suggestions I posted about editing `/etc/udm-iptv.conf`?

**Comment by dmutsaers** [comment]
@dmouwes  It looks like it's working for other users:
https://github.com/fabianishere/udm-iptv/issues/120#issuecomment-2116061629

**Comment by dmouwes** [comment]
I ran the suggested changes mentioned and this is what comes out

root@EM:~# dpkg --configure -a
Setting up udm-iptv (3.0.5) ...
dpkg: error processing package udm-iptv (--configure):
 installed udm-iptv package post-installation script subprocess returned error exit status 128
Errors were encountered while processing:
 udm-iptv

**Comment by erikpost** [comment]
Sorry, afraid I don't know what else to try. The script is working for others with a CGU, and without access to your CGU it is very difficult to debug this remotely. Maybe others here have additional tips.

**Comment by dmutsaers** [comment]
The thing I would try next is a factory reset and start over.

**Comment by fabianishere** [comment]
Please try to install after running `truncate -s 0 /etc/udm-iptv.conf`

**Comment by dmouwes** [comment]
> Please try to install after running `truncate -s 0 /etc/udm-iptv.conf`
I managed to install it and then this showed up:

![Udm-iptverror](https://github.com/user-attachments/assets/cb599462-e991-41cb-acc9-5639a6144a4e)

**Comment by xelAresU** [comment]
I'm also encountering the issue that I cannot install the script:
```
Downloading packages...
Installing packages...
W: The repository '[http://security.debian.org/debian-security stretch/updates](http://security.debian.org/debian-security%20stretch/updates) Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch-backports Release' does not have a Release file.
E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-arm64/Packages  404  Not Found [IP: 151.101.38.132 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-arm64/Packages  404  Not Found [IP: 151.101.38.132 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-arm64/Packages  404  Not Found [IP: 151.101.38.132 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch-backports/main/binary-arm64/Packages  404  Not Found [IP: 151.101.38.132 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
E: Package 'dialog' has no installation candidate
Failed to install dialog... Using readline frontend
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 udm-iptv : Depends: busybox but it is not installable or
                     busybox-static but it is not installable
            Depends: iproute2 but it is not installable
            Depends: iptables but it is not installable
            Recommends: improxy but it is not installable
E: Unable to correct problems, you have held broken packages.
```
is seems that "stretch" has been archived
