### ISSUE TITLE
Breaks on firmware update with Unifi Cloud Gateway Ultra

### ISSUE THREAD

**Issue by rweijnen** [fabianishere/udm-iptv#323]
### Diagnostic Information

Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth4
WAN VLAN: 4 (dev iptv)
WAN DHCP: true (options "-O staticroutes -V IPTV_RG")
WAN Ranges: 213.75.0.0/16  217.166.0.0/16
LAN Interfaces: br661
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
67: iptv@eth4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1512 qdisc noqueue state UP group default qlen 1000
    inet 10.47.128.47/22 brd 10.47.131.255 scope global iptv
       valid_lft forever preferred_lft forever
10.47.128.0/22 proto kernel scope link src 10.47.128.47 
213.75.112.0/21 via 10.47.128.1 metric 267 
=== Service Logs ===
May 24 21:55:23 Cloud-Gateway-Ultra udm-iptvd[140627]: DEBUG[imp_input_report_v1v2@289]: group address 224.0.0.251
May 24 21:55:23 Cloud-Gateway-Ultra udm-iptvd[140627]: INFO[imp_verify_multicast_addr@251]: Group address 224.0.0.251 is Local Network Control Block
May 24 21:55:23 Cloud-Gateway-Ultra udm-iptvd[140627]: DEBUG[main@653]: Data arrive
May 24 21:55:23 Cloud-Gateway-Ultra udm-iptvd[140627]: DEBUG[mcast_recv_igmp@748]: src addr = 0.0.0.0
May 24 21:55:23 Cloud-Gateway-Ultra udm-iptvd[140627]: received interface  4
May 24 21:55:23 Cloud-Gateway-Ultra udm-iptvd[140627]: WARNING[mcast_recv_igmp@753]: Don't exist this VIF 4
May 24 21:55:23 Cloud-Gateway-Ultra udm-iptvd[140627]: DEBUG[main@653]: Data arrive
May 24 21:55:23 Cloud-Gateway-Ultra udm-iptvd[140627]: DEBUG[mcast_recv_igmp@748]: src addr = 10.10.10.10
May 24 21:55:23 Cloud-Gateway-Ultra udm-iptvd[140627]: received interface  67
May 24 21:55:23 Cloud-Gateway-Ultra udm-iptvd[140627]: WARNING[mcast_recv_igmp@759]: Don't exist this Downstream VIF

### Describe the Bug

Works fine with this config: https://github.com/rweijnen/unifi-cloudgateway-ultra/blob/main/udm-iptv.conf
However on firmware update it breaks, need to reinstall.

Tested upgrade from 3.2.12 to 3.2.17 and 3.2.17 to to 4.0.4

### Expected Behavior

udm-iptv files should be persisted across firmware update.
Maybe it can leverage this (if installed) as I can confirm it persists on UCG-U? https://github.com/unifi-utilities/unifios-utilities/tree/main/on-boot-script-2.x

**Comment by dmutsaers** [comment]
Installation across Firmware Updates
Please remember to make a backup of your configuration before a firmware update. Currently, your configuration and installation might or might not persist across firmware updates depending on the type of upgrade (see #120).

https://github.com/fabianishere/udm-iptv#installation-across-firmware-updates

**Comment by fabianishere** [comment]
This is a known issue (#120) and not something I think can be fixed at the moment.

**Comment by spudje** [comment]
Sorry to be blunt, but I'm not that familiar with SSH. How do I create a backup of the configuration and how do I restore it after a firmware update?
