### ISSUE TITLE
UDM Pro Max Not able to select WAN Port in Setup

### ISSUE THREAD

**Issue by apple-kevin** [fabianishere/udm-iptv#335]
### What is your ISP? (if relevant)

KPN

### Diagnostic Information

root@Dream-Machine-Pro-Max:~# 
8]: src addr = 10.15.12.1
Jul 20 21:10:33 Dream-Machine-Pro-Max udm-iptvd[98445]: received interface  15
Jul 20 21:10:33 Dream-Machine-Pro-Max udm-iptvd[98445]: WARNING[mcast_recv_igmp@753]: Don't exist this VIF 15
Jul 20 21:10:33 Dream-Machine-Pro-Max udm-iptvd[98445]: DEBUG[main@653]: Data arrive
Jul 20 21:10:33 Dream-Machine-Pro-Max udm-iptvd[98445]: DEBUG[mcast_recv_igmp@748]: src addr = 10.15.12.1
Jul 20 21:10:33 Dream-Machine-Pro-Max udm-iptvd[98445]: received interface  15
Jul 20 21:10:33 Dream-Machine-Pro-Max udm-iptvd[98445]: WARNING[mcast_recv_igmp@753]: Don't exist this VIF 15
Jul 20 21:10:33 Dream-Machine-Pro-Max udm-iptvd[98445]: DEBUG[main@653]: Data arrive
Jul 20 21:10:33 Dream-Machine-Pro-Max udm-iptvd[98445]: DEBUG[mcast_recv_igmp@748]: src addr = 10.60.184.27
Jul 20 21:10:33 Dream-Machine-Pro-Max udm-iptvd[98445]: received interface  91

### Describe the Bug

Normally during setup you will be asked whether you are using WAN 1 (RJ45) or WAN 2 (SFP).

<img width="561" alt="306396449-1de94d0e-a888-4169-bbb8-4294a38e13ef" src="https://github.com/user-attachments/assets/c1096882-638e-47ea-89e6-d629705ed7a5">

I get this question on my UDM SE but **NOT** on my **UDM Pro Max**.
The rest of the setup is going well.
and since I use SFP I have to choose WAN 2 (eth 9)

For now I solved it myself by changing the configuration file from (eth 8 RJ45) to (eth9 SFP)

<img width="523" alt="Scherm­afbeelding 2024-07-20 om 21 23 32" src="https://github.com/user-attachments/assets/b336231d-2442-426b-bfe9-e9d9c32cd27c">

### Expected Behavior

can this be solved?

**Comment by erikpost** [comment]
This is probably caused because the shortname of the UDM Pro Max is not recognized by the script, and therefore the script cannot configure the options for available WAN interfaces. Can you post the value of `board.shortname` as listed in `/etc/board.info`?

**Comment by apple-kevin** [comment]
@erikpost  Yes of course: board.shortname=UDMPROMAX

**Comment by erikpost** [comment]
I have created a pull request that adds support for the UDM Pro Max. Hopefully @fabianishere can merge this and release a new version shortly and then WAN selection should work on the UDM Pro Max.

**Comment by apple-kevin** [comment]
@fabianishere can you put a update? (3.0.6)
Its stil not working 3.0.5 is still the latest update. (from May)
