### ISSUE TITLE
Uses wrong WAN port for UniFi Cloud Gateway Max

### ISSUE THREAD

**Issue by abontjer** [fabianishere/udm-iptv#338]
### What is your ISP? (if relevant)

KPN

### Diagnostic Information

root@Cloud-Gateway-Max:~# udm-iptv diagnose
Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth8
WAN VLAN: 4 (dev iptv)
WAN DHCP: true (options "-O staticroutes -V IPTV_RG")
WAN Ranges: X.X.X.X/16  X.X.X.X/16
LAN Interfaces: br0
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
Device "iptv" does not exist.
Cannot find device "iptv"
=== Service Logs ===
Jul 27 14:53:09 Cloud-Gateway-Max udm-iptvd[630335]: Device eth8 for iptv does not exist
Jul 27 14:53:09 Cloud-Gateway-Max systemd[1]: udm-iptv.service: Main process exited, code=exited, status=1/FAILURE
Jul 27 14:53:09 Cloud-Gateway-Max systemd[1]: udm-iptv.service: Failed with result 'exit-code'.
Jul 27 14:53:14 Cloud-Gateway-Max systemd[1]: udm-iptv.service: Scheduled restart job, restart counter is at 69.
Jul 27 14:53:14 Cloud-Gateway-Max systemd[1]: Stopped IPTV support for the UniFi Dream Machine.
Jul 27 14:53:14 Cloud-Gateway-Max systemd[1]: Started IPTV support for the UniFi Dream Machine.
Jul 27 14:53:14 Cloud-Gateway-Max udm-iptvd[630491]: Device "eth8" does not exist.
Jul 27 14:53:14 Cloud-Gateway-Max udm-iptvd[630490]: Device eth8 for iptv does not exist
Jul 27 14:53:14 Cloud-Gateway-Max systemd[1]: udm-iptv.service: Main process exited, code=exited, status=1/FAILURE
Jul 27 14:53:14 Cloud-Gateway-Max systemd[1]: udm-iptv.service: Failed with result 'exit-code'.

### Describe the Bug

iptv does not work because udm-iptv is using the wrong (non-existing) WAN port

### Expected Behavior

/etc/udm-iptv.conf should use eth4 as the WAN port for the UniFi Cloud Gateway Max

**Comment by erikpost** [comment]
The UniFi Cloud Gateway Max is not yet in the configuration script. Can you post the value of `board.shortname` as listed in `/etc/board.info` on your device?

As a workaround you can manually override the config by editing `/etc/udm-iptv.conf` and setting `IPTV_WAN_INTERFACE` to the correct WAN interface name (`eth4`). Then restart the udm-iptv service with `systemctl restart udm-iptv`.

**Comment by abontjer** [comment]
The board's short name is `UCGMAX`.

I have already found the workaround you proposed, and it did indeed work.

**Comment by erikpost** [comment]
I created a PR ( #340 ) to add support for the UCG Max in the configuration wizard. Until that is merged by @fabianishere you need to use the workaround and edit the `udm-itpv.conf` by hand.
