### ISSUE TITLE
No Multicast 

### ISSUE THREAD

**Issue by reinierkops** [fabianishere/udm-iptv#354]
### What is your ISP? (if relevant)

KPN

### Diagnostic Information

=== Configuration ===
WAN Interface: eth8
WAN VLAN: 4 (dev iptv)
WAN DHCP: true (options "-O staticroutes -V IPTV_RG")
WAN Ranges: 213.75.0.0/16  217.166.0.0/16
LAN Interfaces: br4
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
=== Service Logs ===
Oct 13 17:01:05 Dream-Machine-SE udm-iptvd[1845274]: DEBUG[init_interface@195]: if_index = 2571
Oct 13 17:01:05 Dream-Machine-SE udm-iptvd[1845274]: DEBUG[init_interface@208]: if_mtu = 9216
Oct 13 17:01:05 Dream-Machine-SE udm-iptvd[1845274]: DEBUG[init_interface@214]: if_falgs = 4163
Oct 13 17:01:05 Dream-Machine-SE udm-iptvd[1845274]: DEBUG[init_interface@178]: iptv's ipv4 address is 10.254.103.163
Oct 13 17:01:05 Dream-Machine-SE udm-iptvd[1845274]: DEBUG[init_interface@195]: if_index = 15258
Oct 13 17:01:05 Dream-Machine-SE udm-iptvd[1845274]: DEBUG[init_interface@208]: if_mtu = 1500
Oct 13 17:01:05 Dream-Machine-SE udm-iptvd[1845274]: DEBUG[init_interface@214]: if_falgs = 4163
Oct 13 17:01:05 Dream-Machine-SE udm-iptvd[1845274]: ERROR[main@619]: exiting.........
Oct 13 17:01:05 Dream-Machine-SE systemd[1]: udm-iptv.service: Main process exited, code=exited, status=1/FAILURE
Oct 13 17:01:05 Dream-Machine-SE systemd[1]: udm-iptv.service: Failed with result 'exit-code'.

### Describe the Bug

TV+ is switching very slow between channels.
When manualy switching to unicast, no problems.

### Expected Behavior

Quick response of switching channels

**Comment by Toomblr** [comment]
Hi @reinierkops, how did you fix this eventually?

**Comment by bramstroker** [comment]
I have this same issue, changing channels very slow 5sec+. how did you resolve @reinierkops ?
