### ISSUE TITLE
Seperate MAC addreses on WAN and IPTV interface

### ISSUE THREAD

**Issue by reinierjh** [fabianishere/udm-iptv#39]
My Internet provider TWEAK NL does not allow the same mac address on iptv and internet wan port (VLAN).
Is it possible to add a different macaddres to the iptv interface? (On a UDM-SE (GA) (UDM-PRO-SE (EA)))

**Comment by fabianishere** [comment]
Hmm, that's a strange requirement. You could try to augment `/usr/lib/udm-iptv/udm-iptv` to change the MAC address after creation:
```diff
ip link add link "$IPTV_WAN_INTERFACE" name "$IPTV_WAN_VLAN_INTERFACE" type vlan id "$IPTV_WAN_VLAN"

+ ip link set dev "$IPTV_WAN_VLAN_INTERFACE" address <mac address>

# Bring VLAN interface up
ip link set dev "$IPTV_WAN_VLAN_INTERFACE" up
```

**Comment by reinierjh** [comment]
Indeed a strange requirement. But the DHCP server is only giving out 1 ip address per mac address. This means that after de iptv ip address is given out the wan/internet address is not routable any more. At the moment i hardcoded the macaddress in the script. 
I changed the "ip link add link "$IPTV_WAN_INTERFACE" name "$IPTV_WAN_VLAN_INTERFACE" type vlan id "$IPTV_WAN_VLAN"" to ip link add link "$IPTV_WAN_INTERFACE" address "00:11:11:11:11:11" name "$IPTV_WAN_VLAN_INTERFACE" type vlan id "$IPTV_WAN_VLAN"

Ofcourse the mac address is derived from the wan mac address. (added 1)

**Comment by fabianishere** [comment]
@reinierjh I am adding an option `IPTV_WAN_VLAN_MAC` to specify a custom MAC address for the VLAN interface. You'll have to specify it manually in `/etc/udm-iptv.conf` for now though:

```diff
# Name of the IPTV VLAN interface
IPTV_WAN_VLAN_INTERFACE="iptv"
+ IPTV_WAN_VLAN_MAC="00:11:11:11:11:11"
```
