### ISSUE TITLE
IPTV works, on demand doesn´t

### ISSUE THREAD

**Issue by apedroheringer** [fabianishere/udm-iptv#48]
Hi fabianishere, it´s me again.

Thank you for this project

As you suggested, yesterday I created a seperate vlan for my iptv, so I could bypass pihole
I thought that pihole was blocking my access to on demand stuff, but it was not (my iptv vlan is configure to serve automatic name server)

I user Vivo (telefonica) Brasil, and here is my udm-iptv-diag

> Please share the following output with the developers:
> === Configuration ===
> WAN Interface: eth8
> WAN Ranges: 172.28.0.0/14  201.0.52.0/23  200.161.71.0/24  177.16.0.0/16
> WAN VLAN: 20 (dev iptv)
> WAN DHCP options: -O staticroutes -V IPTV_RG
> LAN Interfaces: br20
> IGMP Proxy quickleave disabled: false
> IGMP Proxy debug: false
> === IP Link and Route ===
> 43: iptv@eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue qlen 1000
>     inet 10.154.188.196/20 scope global iptv
>        valid_lft forever preferred_lft forever
> 10.154.176.0/20 dev iptv  src 10.154.188.196
> 172.28.0.0/14 via 10.154.176.1 dev iptv  metric 243
> 177.16.30.0/23 via 10.154.176.1 dev iptv  metric 248
> 200.161.71.40/30 via 10.154.176.1 dev iptv  metric 245
> 200.161.71.46/31 via 10.154.176.1 dev iptv  metric 246
> 200.161.71.48/31 via 10.154.176.1 dev iptv  metric 247
> 201.0.52.0/23 via 10.154.176.1 dev iptv  metric 244
> === Service Logs ===
> Jan 26 10:13:28 ubnt systemd[1]: Started IPTV support for the UniFi Dream Machine.
> Jan 26 10:13:29 ubnt udm-iptv[68]: Obtaining IP address for VLAN interface
> Jan 26 10:13:29 ubnt udm-iptv[68]: udhcpc (v1.22.1) started
> Jan 26 10:13:29 ubnt udm-iptv[68]: Sending discover...
> Jan 26 10:13:29 ubnt udm-iptv[68]: Sending select for 10.154.188.196...
> Jan 26 10:13:29 ubnt udm-iptv[68]: Lease of 10.154.188.196 obtained, lease time 7200
> Jan 26 10:13:29 ubnt udm-iptv[68]: NATing IPTV network ranges (if necessary)
> Jan 26 10:13:29 ubnt udm-iptv[68]: Setting up igmpproxy
> Jan 26 10:13:29 ubnt udm-iptv[68]: Starting igmpproxy
> Jan 26 10:27:14 ubnt igmpproxy[68]: MRT_DEL_MFC; Errno(2): No such file or directory

I think that this last line/error appeared after trying to access on demand show, but I´m not sure...
I´ve got my wan range addresses on https://github.com/offspringer/unifi-usg-vivo-fibra/blob/master/config.gateway.json (it´s a repo to enable vivo iptv on a usg). The routes that my UDMpro got are the same described on this json. It also sets a "customized-IPTV Multicast" firewall group for firewall rules, I replicated these rules and made no difference... I also added this "customized-IPTV Multicast" on my wan range addresses but it also made no difference

Can you help me make my on demand stuff works?

Sorry that english is not my first language

Thank you very much! I updated your readme with Vivo´s config

edit: I´m using UDM 1.11 with stock kernel

**Comment by reinierjh** [comment]
For on demand you problably need a RTSP kernel module. (I have the same problem) We tried to compile the kernel module. But could not get it working.

**Comment by apedroheringer** [comment]
> For on demand you problably need a RTSP kernel module. (I have the same problem) We tried to compile the kernel module. But could not get it working.

Thank you for your response. I was able to get it working!
I was looking on the settings of my ISP´s routers, they send me a DNS server on my internet VLan over pppoe but none on my IPTV Vlan
checking the router´s lan DHCP settings they give two DNS addresses to my STBs
On my UDM pro I configured these dns servers as name server on my lan´s iptv vlan and voila, it worked!

I´m just afraid that they might change these dns settings over time...

Here another user made a script to update my isp´s dns  server https://github.com/offspringer/unifi-usg-vivo-fibra/blob/master/update_iptv_dns.sh, but it is for USG and I don´t know how to translate it to the udmpro...

I´ll add these dns servers on the readme of this repo
Thank you for take you time to answer me

**Comment by apedroheringer** [comment]
![20220126_122710](https://user-images.githubusercontent.com/67462182/151220695-4a7b5e4c-116c-4c0a-9883-f1666ea75384.jpg)

Here a picture the configuration of DHCP on my ISP´s router.
I´ll try using these option 60 (MSFT_IPTV,TEF_IPTV) instead of IPTV_RG and see what happens.. I´ll update here when I try it

**Comment by apedroheringer** [comment]
> 

By change option 60 and removing the dns address on demand stop working... I wish I could get these addresses automatically :/

**Comment by apedroheringer** [comment]
> ![20220126_122710](https://user-images.githubusercontent.com/67462182/151220695-4a7b5e4c-116c-4c0a-9883-f1666ea75384.jpg)
> 
> Here a picture the configuration of DHCP on my ISP´s router. I´ll try using these option 60 (MSFT_IPTV,TEF_IPTV) instead of IPTV_RG and see what happens.. I´ll update here when I try it

By changing option 60 and removing the dns address on demand stop working... I wish I could get these addresses automatically :/

**Comment by fabianishere** [comment]
Is it not sufficient to hardcode the DNS servers? Do they change often? It might theoretically possible to automatically update the DNS servers, but is it worth all the hassle?

**Comment by apedroheringer** [comment]
> Is it not sufficient to hardcode the DNS servers? Do they change often? It might theoretically possible to automatically update the DNS servers, but is it worth all the hassle?

On this repo https://github.com/offspringer/unifi-usg-vivo-fibra/blob/master/update_iptv_dns.sh offspringer made this script in case DNS changes, but I talked to him and he said that over an year it never changed, so it doesn´t worth all the hassle :) I´ll just keep it hardcoded. Thank you for your help!
