### ISSUE TITLE
Config lost on upgrade to 1.11.1

### ISSUE THREAD

**Issue by jdrom** [fabianishere/udm-iptv#49]
For those that haven't upgraded their UDMP's yet, perhaps they can collect more details... 

I had to re-configure to get the TV back up and running but it seems like the config was wiped? When I ran `udm-iptv-diag` the output was:
```root@ubnt:/# udm-iptv-diag
Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth8
WAN Ranges: 213.75.0.0/16  217.166.0.0/16
WAN VLAN: 4
WAN DHCP options: -O staticroutes -V IPTV_RG
LAN Interfaces: br0
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: false
=== IP Link and Route ===
/usr/bin/udm-iptv-diag: 31: /usr/bin/udm-iptv-diag: ip: not found
/usr/bin/udm-iptv-diag: 32: /usr/bin/udm-iptv-diag: ip: not found
=== Service Logs ===
Jan 26 15:45:30 ubnt udm-iptv[23807]: ip: SIOCGIFFLAGS: No such device
Jan 26 15:45:30 ubnt udm-iptv[23807]: Obtaining IP address for VLAN interface
Jan 26 15:45:30 ubnt udm-iptv[23807]: udhcpc: SIOCGIFINDEX: No such device
Jan 26 15:45:30 ubnt udm-iptv[23807]: NATing IPTV network ranges (if necessary)
Jan 26 15:45:30 ubnt udm-iptv[23807]: Setting up igmpproxy
Jan 26 15:45:30 ubnt udm-iptv[23807]: Starting igmpproxy
Jan 26 15:45:30 ubnt igmpproxy[23807]: There must be at least 1 Vif as upstream.
Jan 26 15:45:30 ubnt systemd[1]: udm-iptv.service: Main process exited, code=exited, status=255/EXCEPTION
Jan 26 15:45:30 ubnt systemd[1]: udm-iptv.service: Failed with result 'exit-code'.
Jan 26 15:45:30 ubnt systemd[1]: udm-iptv.service: Consumed 136ms CPU time.
```
Which looks like the "default" settings. I was running v2.0.2, did the reconfigure via `dpkg-reconfigure -p medium udm-iptv` to get it back to my correct config:
```Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth9
WAN Ranges: 10.2.0.0/16 10.125.0.0/16
WAN VLAN: 36
WAN DHCP options: -o
LAN Interfaces: br40
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: false
=== IP Link and Route ===
/usr/bin/udm-iptv-diag: 31: /usr/bin/udm-iptv-diag: ip: not found
/usr/bin/udm-iptv-diag: 32: /usr/bin/udm-iptv-diag: ip: not found
=== Service Logs ===
Jan 26 15:45:30 ubnt systemd[1]: udm-iptv.service: Consumed 136ms CPU time.
Jan 26 15:49:05 ubnt systemd[1]: Started IPTV support for the UniFi Dream Machine.
Jan 26 15:49:05 ubnt udm-iptv[27726]: Obtaining IP address for VLAN interface
Jan 26 15:49:05 ubnt udm-iptv[27726]: udhcpc (v1.22.1) started
Jan 26 15:49:05 ubnt udm-iptv[27726]: Sending discover...
Jan 26 15:49:05 ubnt udm-iptv[27726]: Sending select for 10.125.180.72...
Jan 26 15:49:05 ubnt udm-iptv[27726]: Lease of 10.125.180.72 obtained, lease time 573345
Jan 26 15:49:05 ubnt udm-iptv[27726]: NATing IPTV network ranges (if necessary)
Jan 26 15:49:05 ubnt udm-iptv[27726]: Setting up igmpproxy
Jan 26 15:49:05 ubnt udm-iptv[27726]: Starting igmpproxy
```
I've upgraded to v2.0.4 as well now, so I guess we'll see what happens with the next firmware update.

**Comment by fabianishere** [comment]
Unfortunately, I think this is unavoidable due to the way the DPKG cache in UniFi works.

**Comment by jdrom** [comment]
Hmm in that case then, as a workaround, I could use boostchicken's on-boot-script to copy my working config file and restart the service? That wouldn't break anything from your standpoint? 

I guess it's really just a minor inconvenience, but I've been letting the UDMP auto-upgrade at night so waking up with TV broken isn't great... I could just stop the auto-upgrade too...

**Comment by fabianishere** [comment]
Yes, that would work :)

**Comment by reinierjh** [comment]
Would it not be possible to make the config (if it works correctly) readonly? I have the same problem that after an upgrade the default settings are insert in the config file.  (UDM-SE so 2.3.15)

**Comment by fabianishere** [comment]
As far as I know, the config is not overwritten, but is removed all together during the flashing process, after which the package is re-installed (with the default config).

**Comment by reinierjh** [comment]
Nope. The original file is overwritten only with the defaults from your package. (i use a MACADDR value that is still in the file after an upgrade.)
I tested this by adding extra values, and the al stay in the file. But ETHx Vlanid IGMPDebug and BRid are reset to the default.

**Comment by bprskalo** [comment]
@fabianishere 

just to let you know .. after upgrade to 1.11.3 and 2.05 installed .. the original config was applied :-)
