### ISSUE TITLE
Udmp and Init7 - TV7 not working :(

### ISSUE THREAD

**Issue by jaybird-69** [fabianishere/udm-iptv#53]
Hi There, 

Thanks in advance for your help.
Tried to follow the setup guide for my udmp, nothing fancy, but somehow it does not seem to work.
I didn't set any dhcp options and no vlan

many thanks for your help ! :D
udm pro firmware v1.11.0.

diag output:

root@ubnt:/# udm-iptv-diag
Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth9
WAN Ranges: 224.0.0.0/8  239.0.0.0/8
WAN VLAN: 0 (dev iptv)
WAN DHCP options:
LAN Interfaces: br0  br2  br4
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
3: eth9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq qlen 10000
    inet 212.51.129.239/24 scope global dynamic eth9
       valid_lft 1653sec preferred_lft 1653sec
212.51.129.0/24 dev eth9  src 212.51.129.239
=== Service Logs ===
Jan 30 21:01:23 ubnt udm-iptv[14939]: RECV V2 member report   from 192.168.2.253   to 239.0.0.250
Jan 30 21:01:23 ubnt udm-iptv[14939]: Updated route entry for 239.0.0.250 on VIF #2
Jan 30 21:01:24 ubnt udm-iptv[14939]: RECV V2 member report   from 192.168.1.115   to 233.89.188.1
Jan 30 21:01:24 ubnt udm-iptv[14939]: Updated route entry for 233.89.188.1 on VIF #1
Jan 30 21:01:24 ubnt udm-iptv[14939]: The source address 192.168.1.115 for group 233.89.188.1 is from downstream VIF[0]. Ignoring.
Jan 30 21:01:24 ubnt udm-iptv[14939]: RECV V2 member report   from 192.168.4.254   to 224.0.0.2
Jan 30 21:01:24 ubnt udm-iptv[14939]: The IGMP message was from myself. Ignoring.
Jan 30 21:01:24 ubnt udm-iptv[14939]: The IGMP message was local multicast. Ignoring.
Jan 30 21:01:27 ubnt udm-iptv[14939]: The IGMP message was local multicast. Ignoring.
Jan 30 21:01:27 ubnt udm-iptv[14939]: The IGMP message was local multicast. Ignoring.
root@ubnt:/#

**Comment by jaybird-69** [comment]
Hallelujah ! 

After some research and google trad (Init7 is mainly present in Zurich and my german is terrible).

I was missing one range:   in total 224.0.0.0/8, 239.0.0.0/8, 77.109.128.0.0/19

Now it works, thanks !

**Comment by archdesignCH** [comment]
Hallo jaybird-69,
wie konntest du die dritte range ergänzen (77.109.128.0/19)?
Welche Firewall-Einstellungen verwendest du in der UDM Pro damit Multicast von TV7 (Init7) funktioniert?

WAN Interface: eth9
WAN Ranges: 224.0.0.0/8 239.0.0.0/8
WAN VLAN: 0 (dev iptv)
WAN DHCP options: 
LAN Interfaces: br0
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: false
=== IP Link and Route ===
3: eth9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq qlen 10000
    inet 212.51.143.185/24 scope global dynamic eth9
       valid_lft 1778sec preferred_lft 1778sec
212.51.143.0/24 dev eth9  src 212.51.143.185 
=== Service Logs ===
Feb 20 00:49:35 ubnt igmpproxy[539]: The source address 77.109.129.16 for group 239.77.0.184, is not in any valid net for upstream VIF[0].
Feb 20 00:49:45 ubnt igmpproxy[539]: The source address 77.109.129.16 for group 239.77.0.184, is not in any valid net for upstream VIF[0].
Feb 20 00:49:55 ubnt igmpproxy[539]: The source address 77.109.129.16 for group 239.77.0.184, is not in any valid net for upstream VIF[0].
Feb 20 00:50:05 ubnt igmpproxy[539]: The source address 77.109.129.16 for group 239.77.0.184, is not in any valid net for upstream VIF[0].
Feb 20 00:50:16 ubnt igmpproxy[539]: The source address 77.109.129.16 for group 239.77.0.184, is not in any valid net for upstream VIF[0].
Feb 20 00:50:26 ubnt igmpproxy[539]: The source address 77.109.129.16 for group 239.77.0.184, is not in any valid net for upstream VIF[0].
Feb 20 00:50:36 ubnt igmpproxy[539]: The source address 77.109.129.16 for group 239.77.0.184, is not in any valid net for upstream VIF[0].
Feb 20 00:50:46 ubnt igmpproxy[539]: The source address 77.109.129.16 for group 239.77.0.184, is not in any valid net for upstream VIF[0].
Feb 20 00:50:56 ubnt igmpproxy[539]: The source address 77.109.129.16 for group 239.77.0.184, is not in any valid net for upstream VIF[0].
Feb 20 00:51:06 ubnt igmpproxy[539]: The source address 77.109.129.16 for group 239.77.0.184, is not in any valid net for upstream VIF[0].

Besten Dank für deine Unterstützung.

**Comment by jaybird-69** [comment]
Hi,



Did your try to add the 3rd IP in your wan ranges ? It does not seem to be the case on your config file:


WAN Ranges: 224.0.0.0/8, 239.0.0.0/8,  77.109.128.0/19


as for the firewall, I created a network group with all the multicast network addresses, and allowed UDP traffic with the network group as source. 


Since only my udproxy is getting it, the destination is my NAS's LAN IP.


I created a vlan to avoid any issues with multicast but i


Hope that helped,

**Comment by archdesignCH** [comment]
Hi,
finally it worked with the 3rd IP ! Thanks a lot ! :)
-> Wirth the network group (224.0.0.0/8, 239.0.0.0/8,  77.109.128.0/19) and the firewall rules from this site (https://supportblog.ch/init7-tv7-auf-unifi-security-gateway-usg-einrichten/) I could now use TV7 with Multicast over UDM Pro (1.11.0). I allowd the protocol "PIM" an IGMP on WAN LOCAL to destination "network group" -> maybe the protocoll PIM is not necessery, but I allow it.
Thanks a lot for your tip 👍 
Best wishes from Zurich (Oerlikon)
