### ISSUE TITLE
Stuttering video 

### ISSUE THREAD

**Issue by dickydick1963** [fabianishere/udm-iptv#54]
Hello,

Thank you for this great guide everything works very well but....
When watching tv so now and a while I have stuttering video, as well in live television as stored television.
I am in the Netherlands and use KPN FTTH

My diag output is:

=== Configuration ===
WAN Interface: eth8
WAN Ranges: 213.75.0.0/16  217.166.0.0/16
WAN VLAN: 4 (dev iptv)
WAN DHCP options: -O staticroutes -V IPTV_RG
LAN Interfaces: br5
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
49: iptv@eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue qlen 1000
    inet 10.148.87.175/18 brd 10.148.127.255 scope global iptv
       valid_lft forever preferred_lft forever
10.148.64.0/18 dev iptv  src 10.148.87.175 
213.75.112.0/21 via 10.148.64.1 dev iptv  metric 249 
=== Service Logs ===
Feb 01 14:03:06 ubnt udm-iptv[19788]: The IGMP message was from myself. Ignoring.
Feb 01 14:03:08 ubnt udm-iptv[19788]: The IGMP message was local multicast. Ignoring.
Feb 01 14:03:08 ubnt udm-iptv[19788]: RECV V2 member report   from 192.168.2.6     to 224.3.2.6
Feb 01 14:03:08 ubnt udm-iptv[19788]: Updated route entry for 224.3.2.6 on VIF #0
Feb 01 14:03:08 ubnt udm-iptv[19788]: Adding MFC: 213.75.167.58 -> 224.3.2.6, InpVIf: 1
Feb 01 14:03:10 ubnt udm-iptv[19788]: RECV V2 member report   from 192.168.2.254   to 224.0.0.251
Feb 01 14:03:10 ubnt udm-iptv[19788]: The IGMP message was from myself. Ignoring.
Feb 01 14:03:10 ubnt udm-iptv[19788]: RECV V2 member report   from 192.168.2.69    to 224.3.2.6
Feb 01 14:03:10 ubnt udm-iptv[19788]: Updated route entry for 224.3.2.6 on VIF #0
Feb 01 14:03:10 ubnt udm-iptv[19788]: Adding MFC: 213.75.167.58 -> 224.3.2.6, InpVIf: 1

**Comment by fabianishere** [comment]
You have a separate VLAN for your IPTV decoders, correct?

Is there a chance that the stutters are caused by saturation of your WAN link or internal network? If there's too much traffic, it could happen that your video stutters.

**Comment by dickydick1963** [comment]
Indeed I have separate VLAN for IPTV, My WAN link is 1 Gb and my network fully Ubiquiti 1 Gb.
It happens also at night when we only using one stb, while testing my other two stb's did also stutter, and practically no other traffic. On my USG-3P I did not have this problem.  Netflix and others have no problems just the KPN TV.

**Comment by fabianishere** [comment]
IGMP snooping is also enabled on your IPTV network and switches?

**Comment by dickydick1963** [comment]
Yes it is, I changed the cable from the DSM and NT/FTU problem solved!
