### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Meesjee** [fabianishere/udm-iptv#62]
Hi,

Ik heb de UDM-Pro aan mijn XS4ALL (KPN) STB gehangen. 
Ik krijg alleen vanaf de SSH de volende error

```
Package dialog is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'dialog' has no installation candidate

```

Ligt dit aan mij? Zo ja kan ik dit makkelijk oplossen?

**Comment by reinierjh** [comment]
Je hebt wel de handleiding gevolgd:
apt install dialog
daarme zou dialog geïnstalleerd moeten worden. eventueel en apt update ervoor uitvoeren.

**Comment by Meesjee** [comment]
Ja indd na een apt update en upgrade doet de TV het!
Dankjewel!
