### ISSUE TITLE
udm-iptv will not start

### ISSUE THREAD

**Issue by slafc94** [fabianishere/udm-iptv#63]
Last night I upgraded to UniFi OS UDM Pro 1.11.1

Tried to install this service again and now my iptv service will not start and it gives an igmpproxy error, any ideas?

● udm-iptv.service - IPTV support for the UniFi Dream Machine
   Loaded: loaded (/lib/systemd/system/udm-iptv.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2022-02-06 12:16:15 GMT; 3s ago
  Process: 28044 ExecStart=/usr/lib/udm-iptv/udm-iptv start (code=exited, status=255/EXCEPTION)
 Main PID: 28044 (code=exited, status=255/EXCEPTION)
      CPU: 131ms

Feb 06 12:16:15 ubnt systemd[1]: udm-iptv.service: Main process exited, code=exited, status=255/EXCEPTION
Feb 06 12:16:15 ubnt systemd[1]: udm-iptv.service: Failed with result 'exit-code'.
Feb 06 12:16:15 ubnt systemd[1]: udm-iptv.service: Consumed 131ms CPU time.

root@ubnt:/etc# udm-iptv-diag
Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth8
WAN Ranges: 224.0.0.0/4  109.159.247.0/24
WAN VLAN: 0 (dev iptv)
WAN DHCP options: -O staticroutes -V IPTV_RG
LAN Interfaces: br100
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: false
=== IP Link and Route ===
4: eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq qlen 1000
    inet 10.20.30.2/8 brd 10.255.255.255 scope global eth8
       valid_lft forever preferred_lft forever
    inet 10.20.30.1/32 scope global eth8
       valid_lft forever preferred_lft forever
10.0.0.0/8 dev eth8  src 10.20.30.2
=== Service Logs ===
Feb 06 12:17:45 ubnt systemd[1]: Stopped IPTV support for the UniFi Dream Machine.
Feb 06 12:17:45 ubnt systemd[1]: udm-iptv.service: Consumed 131ms CPU time.
Feb 06 12:17:45 ubnt systemd[1]: Started IPTV support for the UniFi Dream Machine.
Feb 06 12:17:45 ubnt udm-iptv[31718]: NATing IPTV network ranges (if necessary)
Feb 06 12:17:45 ubnt udm-iptv[31718]: Setting up igmpproxy
Feb 06 12:17:45 ubnt udm-iptv[31718]: Starting igmpproxy
Feb 06 12:17:45 ubnt igmpproxy[31718]: MC-Router API already in use; Errno(98): Address already in use
Feb 06 12:17:45 ubnt systemd[1]: udm-iptv.service: Main process exited, code=exited, status=255/EXCEPTION
Feb 06 12:17:45 ubnt systemd[1]: udm-iptv.service: Failed with result 'exit-code'.
Feb 06 12:17:45 ubnt systemd[1]: udm-iptv.service: Consumed 141ms CPU time.

**Comment by slafc94** [comment]
IPTV works again once I manually created 15-iptv.sh outside of the unifi-os shell

**Comment by fabianishere** [comment]
You should remove the `15-iptv.sh` script in `/mnt/data/on_boot.d`. That’s only necessary for the old version.

**Comment by slafc94** [comment]
Is there a specific way to stop the process that was created when the 15-iptv.sh script was ran?

**Comment by fabianishere** [comment]
`podman stop iptv` or just reboot the device.

**Comment by slafc94** [comment]
ok, so I've removed all of the old references to 15-iptv.sh and this seems to work. The only issue I have now is getting a shell script to run after a reboot which starts a cronjob to check for a dummy IP on "eth8". Not really sure why this isn't running when it's in the /mnt/data/on_boot.d/ directory

**Comment by fabianishere** [comment]
It might not be possible to launch a cronjob within UbiOS. Maybe that’s something you should do in UniFi OS.

The correct approach is probably to monitor netlink events using `ip monitor` and check whether the IP address was removed on eth8.
