### ISSUE TITLE
UDM WAN pppo MTU and udm-iptv

### ISSUE THREAD

**Issue by StreborStrebor** [fabianishere/udm-iptv#68]
The UDM by default sets ppp0 with MTU 1492, eth4 with MTU 1500 and eth4.6 MTU 1500

To avoid broken VPN tunnels and other issues, it's desired to set:
eth4 mtu 1512
eth4.6 mtu 1508
ppp0 mtu 1500

This (onboot) script does that:

```
sed -i 's/ 1492/ 1500/g' /etc/ppp/peers/ppp0
ip link set dev eth4 mtu 1512
ip link set dev eth4.6 mtu 1508
ifconfig eth4 down
ifconfig eth4 up
killall pppd
```

After running this script (manually or with onboot) checking the MTU with this page ( http://www.letmecheck.it/mtu-test.php ) shows the ppp0 MTU is increased to 1500. VPN tunnels and heavy traffic really like this.

However, the udm-iptv (v 2.04) script does not. It breaks KPN TV.

Any chance you could take a look at what is breaking? 
Any way to get these two to work in harmony?

Some good background info on the unifi community forum can be found here:
https://community.ui.com/questions/Feature-Request-UDM-Pro-PPPoE-RFC4638-1500-MTU-MRU-for-PPP/b5c1fcf6-bee5-4fc7-ae00-c8ce2bf2e724

**Comment by fabianishere** [comment]
Is the script giving you any errors? Could you post the output of `udm-iptv-diag`?

I suspect you need to adjust the MTU of the `iptv` VLAN interface as well.
