### ISSUE TITLE
Dialog is removed after purging

### ISSUE THREAD

**Issue by BeekerMuppet** [fabianishere/udm-iptv#69]
Hi,
i thought I had a major issue (didn't, it was KPN), so I removed everything using the purge command. 
When I tried reinstalling, the _dialog_ command was no longer available. You will notice this in the feedback on **apt install dialog ./igmpproxy_0.3-1_arm64.deb ./udm-iptv_2.0.5_all.deb**

So, I re-installed 11.1 via the ubiquiti website using the ssh command, (**ubnt-upgrade <firmware_url>**). Be aware, you have to run this command OUTSIDE the Unifi-os shell. This worked and got _Dialog_ back to work again. 
Just so you know

**Comment by reinierjh** [comment]
I think an "apt update" should be done before the installation.
Then Dialog is available as a package to be installed.

**Comment by fabianishere** [comment]
@reinierjh is right. I have updated the instructions to include an `apt update`: [effc4a8](https://github.com/fabianishere/udm-iptv/commit/effc4a87eba44cfe0585b7863df45967e314de98)
