### ISSUE TITLE
Arris VIP5202 - Could not download the system software

### ISSUE THREAD

**Issue by squadramunter** [fabianishere/udm-iptv#96]
### What is your ISP? (if relevant)

Solcon

### Diagnostic Information

I try to setup my STB Arris VIP5202 but it fails on downloading the system software with Error4.

When the software is already downloaded the TV streams works without any problems but I can't update the devices anymore.

Do you know what I need to setup for this or has it something to do with the config?

### Describe the Bug

Not able to download system software causing error 4 on Arris VIP5202

### Expected Behavior

When connected it has to download the system software directly.

**Comment by squadramunter** [comment]
`Please share the following output with the developers:
=== Configuration ===
WAN Interface: eth8
WAN Ranges: 10.0.0.0/8  10.252.0.0/16  10.253.0.0/16  217.166.0.0/16
WAN VLAN: 188 (dev iptv)
WAN DHCP options: -O staticroutes -V IPTV_RG
LAN Interfaces: br188
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
45: iptv@eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue qlen 1000
    inet 10.71.93.82/20 scope global iptv
       valid_lft forever preferred_lft forever
10.0.0.0/8 via 10.71.80.1 dev iptv  metric 245
10.71.80.0/20 dev iptv  src 10.71.93.82
=== Service Logs ===
Mar 12 17:54:06 ubnt udm-iptv[20048]: The IGMP message was from myself. Ignoring.
Mar 12 17:54:06 ubnt udm-iptv[20048]: Route activation request from 10.71.93.82 for 225.0.71.1 is from myself. Ignoring.
Mar 12 17:54:07 ubnt udm-iptv[20048]: RECV V2 member report   from 10.71.93.82     to 224.0.251.124
Mar 12 17:54:07 ubnt udm-iptv[20048]: The IGMP message was from myself. Ignoring.
Mar 12 17:54:07 ubnt udm-iptv[20048]: Route activation request from 10.71.93.82 for 224.0.251.124 is from myself. Ignoring.
Mar 12 17:54:07 ubnt udm-iptv[20048]: RECV V2 member report   from 10.71.93.82     to 233.89.188.1
Mar 12 17:54:07 ubnt udm-iptv[20048]: The IGMP message was from myself. Ignoring.
Mar 12 17:54:07 ubnt udm-iptv[20048]: Route activation request from 10.71.93.82 for 233.89.188.1 is from myself. Ignoring.
Mar 12 17:54:08 ubnt udm-iptv[20048]: RECV V2 member report   from 10.71.93.82     to 224.0.0.251
Mar 12 17:54:08 ubnt udm-iptv[20048]: The IGMP message was from myself. Ignoring.`

**Comment by fabianishere** [comment]
I suspect a firewall issue. Could you try changing `IPTV_WAN_RANGES` to `0.0.0.0/0`?

**Comment by squadramunter** [comment]
No, this does not seem to change anything about it.  The websites says it needs the following to make it work.

Specificaties voor TV (IPTV)
Routed Mode configuratie:

De modem / router functioneert in dit geval als eind-apparaat in het IPTV netwerk, daarom moet je IGMP proxy inschakelen (IGMPv2). Daarnaast moet alle netwerk apparatuur tussen de router en de TV-ontvanger, IGMPv2 ondersteunen en IGMP snooping aan hebben staan. Dit zorgt ervoor dat het multicast TV-verkeer alleen op de poorten van de switch wordt aangeboden, waarop de TV ontvanger is aangesloten.

De modem / router krijgt op basis van de waarde van DHCP optie 60 (Vendor Class Identifier) een IP adres in het IPTV netwerk. Deze waarde moet gelijk zijn aan de string IPTV_RG (ASCII).

De modem / router krijgt vervolgens van de DHCP server de volgende DHCP opties terug:

DHCP optie 15 (Domain Name): Deze dient de modem / router te gebruiken binnen het IPTV netwerk
DHCP optie 42 (Network Time Protocol Servers): Deze dient de modem / router te gebruiken binnen het IPTV netwerk
DHCP optie 43 (Vendor-Specific Information): Deze dient opgeslagen te worden in de modem / router en gerepliceerd te worden van WAN naar LAN op het moment dat de TV ontvanger een DHCP verzoek naar de modem / router doet.
DHCP optie 121 (Classless Static Route): Deze dient de modem / router te gebruiken om het IPTV verkeer naar het IPTV netwerk te routeren.

**Comment by fabianishere** [comment]
Are you using the DNS servers given by your ISP?

**Comment by squadramunter** [comment]
Yes I use the DNS Servers given by my ISP

212.45.45.45 and 212.45.33.3

**Comment by squadramunter** [comment]
If you like I can post my Fritz!Box log to investigate this further?

**Comment by fabianishere** [comment]
Yes, that could help. Otherwise, you'll need to create a packet trace of your network.

**Comment by squadramunter** [comment]
[support FRITZ.Box 7530 164.07.25i_11.03.22_2058.txt](https://github.com/fabianishere/udm-iptv/files/8240187/support.FRITZ.Box.7530.164.07.25i_11.03.22_2058.txt)

**Comment by squadramunter** [comment]
Starting at line 17882 might be helping you to find into this issue

**Comment by squadramunter** [comment]
I need to say normally I don't use the Fritz!Box but only for downloading the software on the STB because of this issue. Otherwise I use only my UDM Pro. I am going to make a packet trace of the device when it is requesting for the software. I will post this soon

**Comment by squadramunter** [comment]
I did email you a WeTransfer link since I cannot upload it here due to the size limit. 

Here is the link: https://we.tl/t-bS2SRTgxlm

**Comment by squadramunter** [comment]
Seems it requests some information to stbconfig.solcon.tv with A record pointing to 10.1.9.150

**Comment by fabianishere** [comment]
Hmm, everything looks to be normal in the trace.

I stumbled upon this [forum topic](https://community.ui.com/questions/SOLVED-Solcon-internet-and-IPTV-working-via-Unifi-USG3p-and-replacing-the-Fritzbox-7530/6160468a-1649-416c-9753-b0fe0747f292?page=1) discussing Solcon IPTV with the UniFi USG.

Apparently, the author needed to specify _Option: (43) Vendor-Specific Information_ on their local network in order to get their STB to work (an Amino device). Note sure if this also applied to your situation.

**Comment by squadramunter** [comment]
If I want to add this it says it's already in use

**Comment by squadramunter** [comment]
Could you explain why WAN IPTV is on LAN8 for UDM PRO? I see that my WAN (LAN Interface) is on port 9.

**Comment by squadramunter** [comment]
![image](https://user-images.githubusercontent.com/26835124/158410435-32780f7e-e80a-4e47-b201-9fd3f298b7f1.png)

**Comment by squadramunter** [comment]
Mm interesting. So on Port 8 it is receiving a IP but not for Port 9 so far I can see. Can you explain why this is?

**Comment by reinierjh** [comment]
> Could you explain why WAN IPTV is on LAN8 for UDM PRO? I see that my WAN (LAN Interface) is on port 9.

That's easy. The web interface starts at port1
The device starts at eth0 so....
web interface port9 is device interface eth8..

**Comment by squadramunter** [comment]
That makes sense.  Stil wondering why it won't download the STB software on first boot. Can I try to pass trough the traffic directly to the STB or does that not work?

**Comment by reinierjh** [comment]
As fabian already told you you have to create option 43 in the dchp settings on the lan network the device is active.
If you look at the Fritz config you see that DHCP option 43 is replicated.
This is something the UDM cannot do. So you have to recreate the setting. Everything seems to be in the forum topic posted by Fabian.
According to the Fritz Config al these settings should be replicated.
replicate_dhcpoptions = "17", "33", "40", "41", "43", "72", "140", "141", "142", "166", "170", "171", "172";

**Comment by squadramunter** [comment]
> 

Noob question here. Can you explain how I can apply this for my UDM Pro?

Like to have them applied but don't know how exactly.

**Comment by reinierjh** [comment]
Option43 should be set in the network application. 
It's a setting on the configuration of the network. (DHCP)
![image](https://user-images.githubusercontent.com/34122078/158561339-de3e1d34-43d9-4a30-9ebc-83b23f62f144.png)
Hmm i see that UNIFI also uses option43.

**Comment by squadramunter** [comment]
I think I would use the Fritz!Box as a workaround to get everything installed for now. I close this issue. If someone manage this to get it to work they can reopen this.
