### ISSUE TITLE
stb-nmc-400 error on the stb

### ISSUE THREAD

**Issue by Thomvh** [fabianishere/udm-iptv#99]
### What is your ISP? (if relevant)

KPN

### Diagnostic Information

=== Configuration ===
WAN Interface: eth8
WAN Ranges: 213.75.0.0/16 217.166.0.0/16
WAN VLAN: 4 (dev iptv)
WAN DHCP options: -O staticroutes -V IPTV_RG
LAN Interfaces: br0 br5
IGMP Proxy quickleave disabled: false
IGMP Proxy debug: true
=== IP Link and Route ===
37: iptv@eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    inet 10.181.104.103/22 brd 10.181.107.255 scope global iptv
       valid_lft forever preferred_lft forever
10.181.104.0/22 proto kernel scope link src 10.181.104.103
213.75.112.0/21 via 10.181.104.1 metric 237
=== Service Logs ===
Mar 14 22:03:35 ubnt udm-iptv[62]: RECV V2 member report   from 10.0.5.1        to 233.89.188.1
Mar 14 22:03:35 ubnt udm-iptv[62]: The IGMP message was from myself. Ignoring.
Mar 14 22:03:35 ubnt udm-iptv[62]: The source address 10.0.5.1 for group 233.89.188.1 is from downstream VIF[0]. Ignoring.
Mar 14 22:03:36 ubnt udm-iptv[62]: RECV V2 member report   from 10.0.1.92       to 239.254.127.63
Mar 14 22:03:36 ubnt udm-iptv[62]: Updated route entry for 239.254.127.63 on VIF #0
Mar 14 22:03:36 ubnt udm-iptv[62]: RECV V2 member report   from 10.0.1.190      to 225.0.71.1
Mar 14 22:03:36 ubnt udm-iptv[62]: Updated route entry for 225.0.71.1 on VIF #0
Mar 14 22:03:38 ubnt udm-iptv[62]: The source address 10.0.1.1 for group 233.89.188.1 is from downstream VIF[0]. Ignoring.
Mar 14 22:03:38 ubnt udm-iptv[62]: Route activation request from 10.181.104.103 for 233.89.188.1 is from myself. Ignoring.
Mar 14 22:03:39 ubnt udm-iptv[62]: The IGMP message was local multicast. Ignoring.

### Describe the Bug

Every now and then the STB throws an stb-nmc-400 code and gets stuck. Have to change channels to get it back to working again. This mostly happens when two tv's share the same channel. But also happens randomly when only a single TV runs.

### Expected Behavior

No error :)

**Comment by squadramunter** [comment]
Since you say changing channels will help to solve it do you have a issue the screen freezes after 20 minutes or so? I got a similar issue I think as you unless I do not get a warning instead my screen is totally frozen and when I switch to another channel it works for like 20 - 30 minutes without any issue.

**Comment by Thomvh** [comment]
For me it seems to mostly be triggered by two tv's sharing the same channel. There is not really a timeframe that I can time it on.

**Comment by fabianishere** [comment]
Could you try to disable quickleave using `dpkg-reconfigure -p low udm-iptv`?

**Comment by Multied1** [comment]
What helpt for me 2 years ago with my edgerouter 4 with KPN routed iptv is to make a dedicated subnet  or vlan for multicast traffic and be sure to enable igmp snooping on your switches. I had quick leave enabled on my ER4 but the UDM is a different box so...

I'm using the script for the UDM pro from Fabian with KPN routed IPTV now and it works like a charm🤗

**Comment by Thomvh** [comment]
> Could you try to disable quickleave using `dpkg-reconfigure -p low udm-iptv`?

Have disabled it. Will report back!

**Comment by Thomvh** [comment]
Okay, after testing the problems still persist.

**Comment by Thomvh** [comment]
I will try to move it all to a seperate VLAN in the hopes that works better.

**Comment by raad1960** [comment]
Any updates to this problem? I have the same issue. Installed latest udm-iptv release, but problem remains.  Error message appears every 10 minutes or so, with an occasional freeze in between.   It freezes for a 2 seconds and then recovers, but if the freeze lasts longer, the error message comes up. Then I have to switch channels which fixes it.
